In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"

headers = {
    "User-Agent": "MyDataAnalysisBot/1.0 (fk9822647@gmail.com)"
}


response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

table = soup.find("table", class_="wikitable sortable")

print("Table found:", table is not None)

df = pd.read_html(StringIO(str(table)))[0]

pd.set_option("display.max_rows", 100)

print(df)

Table found: True
    Rank                                 Name  \
0      1                              Walmart
1      2                               Amazon
2      3                   UnitedHealth Group
3      4                                Apple
4      5                           CVS Health
5      6                   Berkshire Hathaway
6      7                             Alphabet
7      8                          Exxon Mobil
8      9                 McKesson Corporation
9     10                              Cencora
10    11                       JPMorgan Chase
11    12                     Costco Wholesale
12    13                                Cigna
13    14                            Microsoft
14    15                      Cardinal Health
15    16                              Chevron
16    17                      Bank of America
17    18                       General Motors
18    19                           Ford Motor
19    20                      Elevance Health
20    21                            Citigroup
21    22                       Meta Platforms
22    23                              Centene
23    24                       The Home Depot
24    25                           Fannie Mae
25    26             Walgreens Boots Alliance
26    27                               Kroger
27    28                          Phillips 66
28    29                   Marathon Petroleum
29    30               Verizon Communications
30    31                               Nvidia
31    32                  Goldman Sachs Group
32    33                          Wells Fargo
33    34                        Valero Energy
34    35                              Comcast
35    36                 State Farm Insurance
36    37                                 AT&T
37    38                          Freddie Mac
38    39                               Humana
39    40                       Morgan Stanley
40    41                               Target
41    42                         StoneX Group
42    43                                Tesla
43    44                    Dell Technologies
44    45                              PepsiCo
45    46                          Walt Disney
46    47                United Parcel Service
47    48                    Johnson & Johnson
48    49                                FedEx
49    50               Archer Daniels Midland
50    51                     Procter & Gamble
51    52                               Lowe's
52    53             Energy Transfer Partners
53    54                                  RTX
54    55                           Albertsons
55    56                                Sysco
56    57                          Progressive
57    58                     American Express
58    59                      Lockheed Martin
59    60                              MetLife
60    61                       HCA Healthcare
61    62                 Prudential Financial
62    63                               Boeing
63    64                          Caterpillar
64    65                                Merck
65    66                             Allstate
66    67                               Pfizer
67    68                                  IBM
68    69      New York Life Insurance Company
69    70                      Delta Air Lines
70    71                 Publix Super Markets
71    72  Nationwide Mutual Insurance Company
72    73                            TD Synnex
73    74             United Airlines Holdings
74    75                       ConocoPhillips
75    76                                  TJX
76    77                               AbbVie
77    78         Enterprise Products Partners
78    79               Charter Communications
79    80               Performance Food Group
80    81              American Airlines Group
81    82                Capital One Financial
82    83                        Cisco Systems
83    84                                   HP
84    85                          Tyson Foods
85    86                                Intel
86    87                               Oracle
87    88                             Broadcom
88    89                                Deere
89    90                                 Nike
90    91       Liberty Mutual Insurance Group
91    92                   Plains GP Holdings
92    93                                 USAA
93    94                 Bristol-Myers Squibb
94    95                 Ingram Micro Holding
95    96                     General Dynamics
96    97                            Coca-Cola
97    98                                 TIAA
98    99                            Travelers
99   100                            Eli Lilly

                               Industry  Revenue (USD millions)  \
0                                Retail                  680985
1            Retail and cloud computing                  637959
2                            Healthcare                  400278
3                            Technology                  391035
4                            Healthcare                  372809
5                          Conglomerate                  371433
6        Technology and cloud computing                  350018
7                             Petroleum                  349595
8                            Healthcare                  308951
9                    Pharmacy wholesale                  293959
10                           Financials                  278906
11                               Retail                  254453
12                     Health insurance                  247121
13       Technology and cloud computing                  245122
14                           Healthcare                  226827
15                            Petroleum                  202792
16                           Financials                  192434
17                           Automotive                  187442
18                           Automotive                  184992
19                           Healthcare                  177011
20                           Financials                  170757
21                           Technology                  164501
22                           Healthcare                  163071
23                               Retail                  159514
24                           Financials                  152670
25                       Pharmaceutical                  147658
26                               Retail                  147123
27                            Petroleum                  145496
28                            Petroleum                  140412
29                   Telecommunications                  134788
30                           Technology                  130497
31                           Financials                  126853
32                           Financials                  125397
33                            Petroleum                  123974
34                   Telecommunications                  123731
35                           Financials                  122951
36  Conglomerate and telecommunications                  122336
37                           Financials                  122052
38                     Health insurance                  117761
39                           Financials                  107285
40                               Retail                  106566
41                           Financials                   99888
42                Automotive and energy                   97690
43                           Technology                   95567
44                             Beverage                   91854
45                                Media                   91361
46                       Transportation                   91070
47                       Pharmaceutical                   88821
48                       Transportation                   87693
49                        Food industry                   85530
50      Consumer products manufacturing                   84039
51                               Retail                   83674
52                            Petroleum                   82671
53                Aerospace and defense                   80739
54                               Retail                   79238
55                      Food processing                   78844
56                            Insurance                   75372
57                           Financials                   74201
58                Aerospace and defense                   71043
59                           Financials                   70986
60                           Healthcare                   70603
61                           Financials                   70405
62                Aerospace and defense                   66517
63                            Machinery                   64809
64              Pharmaceutical industry                   64168
65                            Insurance                   64106
66              Pharmaceutical industry                   63627
67       Technology and cloud computing                   62753
68                            Insurance                   62639
69                              Airline                   61643
70                               Retail                   60177
71                           Financials                   58646
72               Information Technology                   58452
73                              Airline                   57063
74                            Petroleum                   56953
75                               Retail                   56360
76                       Pharmaceutical                   56334
77                            Petroleum                   56219
78                   Telecommunications                   55085
79                      Food processing                   54681
80                              Airline                   54211
81                           Financials                   53938
82       Telecom hardware manufacturing                   53803
83                           Technology                   53559
84                      Food processing                   53309
85                           Technology                   53101
86                           Technology                   52961
87                           Technology                   52432
88            Agriculture manufacturing                   51716
89                              Apparel                   51361
90                            Insurance                   50429
91                            Petroleum                   50073
92                            Insurance                   48560
93                       Pharmaceutical                   48300
94                           Technology                   47984
95                Aerospace and defense                   47716
96                             Beverage                   47061
97                           Financials                   46946
98                            Insurance                   46423
99                       Pharmaceutical                   45043

   Revenue growth  Employees                   Headquarters
0            5.1%    2100000          Bentonville, Arkansas
1           11.0%    1556000            Seattle, Washington
2            7.7%     400000          Minnetonka, Minnesota
3            2.0%     164000          Cupertino, California
4            4.2%     259500       Woonsocket, Rhode Island
5            1.9%     392400                Omaha, Nebraska
6           13.9%     183323      Mountain View, California
7            1.5%      60900                  Spring, Texas
8           11.7%      48000                  Irving, Texas
9           12.1%      44000     Conshohocken, Pennsylvania
10          16.5%     317233        New York City, New York
11           5.0%     333000           Issaquah, Washington
12          26.6%      72398        Bloomfield, Connecticut
13          15.7%     228000            Redmond, Washington
14          10.6%      48411                   Dublin, Ohio
15           0.9%      45298                 Houston, Texas
16          11.9%     213193      Charlotte, North Carolina
17           9.1%     162000              Detroit, Michigan
18           5.0%     171000             Dearborn, Michigan
19           3.3%     103679          Indianapolis, Indiana
20           8.9%     227855        New York City, New York
21          21.9%      74067         Menlo Park, California
22           5.9%      60500            St. Louis, Missouri
23           4.5%     470100               Atlanta, Georgia
24           8.1%       8200               Washington, D.C.
25           6.2%     252500            Deerfield, Illinois
26          -1.9%     409000               Cincinnati, Ohio
27          -2.9%      13200                 Houston, Texas
28          -6.6%      18300                  Findlay, Ohio
29           0.6%      99600        New York City, New York
30         114.2%      36000        Santa Clara, California
31          17.0%      46500        New York City, New York
32           8.7%     217502      San Francisco, California
33         -10.8%       9910             San Antonio, Texas
34           1.8%     182000     Philadelphia, Pennsylvania
35          18.0%      67381          Bloomington, Illinois
36          -0.1%     140990                  Dallas, Texas
37          13.0%       8090               McLean, Virginia
38          10.7%      65680           Louisville, Kentucky
39          11.5%      80478        New York City, New York
40          -0.8%     440000         Minneapolis, Minnesota
41          64.1%       4500        New York City, New York
42           0.9%     125665                  Austin, Texas
43           8.1%     108000              Round Rock, Texas
44           0.4%     319000             Purchase, New York
45           2.8%     205040            Burbank, California
46           0.1%     372180               Atlanta, Georgia
47          -6.7%     138100      New Brunswick, New Jersey
48          -2.7%     422100             Memphis, Tennessee
49          -8.9%      43213              Chicago, Illinois
50           2.5%     108000               Cincinnati, Ohio
51          -3.1%     215500    Mooresville, North Carolina
52           5.2%      16248                  Dallas, Texas
53          17.1%     186000     Arlington County, Virginia
54           2.0%     196650                   Boise, Idaho
55           3.3%      76000                 Houston, Texas
56          21.4%      66308         Mayfield Village, Ohio
57          10.1%      75100        New York City, New York
58           5.1%     121000             Bethesda, Maryland
59           6.1%      45000        New York City, New York
60           8.7%     271000           Nashville, Tennessee
61          30.4%      37936             Newark, New Jersey
62         -14.5%     172000     Arlington County, Virginia
63          -3.4%     112900                  Irving, Texas
64           6.7%      74000         Kenilworth, New Jersey
65          12.3%      55200  Northfield Township, Illinois
66           8.8%      81000        New York City, New York
67           1.4%     284500               Armonk, New York
68          15.3%      15131        New York City, New York
69           6.2%     103000               Atlanta, Georgia
70           4.6%     255000              Lakeland, Florida
71           7.4%      22453                 Columbus, Ohio
72           1.6%      25750            Clearwater, Florida
73           6.2%     107300              Chicago, Illinois
74          -2.8%      11800                 Houston, Texas
75           4.0%     364000      Framingham, Massachusetts
76           3.7%      55000           Lake Bluff, Illinois
77          13.1%       7800                 Houston, Texas
78           0.9%      94500          Stamford, Connecticut
79           2.5%      36815             Richmond, Virginia
80           2.7%     133300              Fort Worth, Texas
81           9.0%      52600               Tysons, Virginia
82          -5.6%      90400           San Jose, California
83          -0.3%      58000          Palo Alto, California
84           0.8%     138000           Springdale, Arkansas
85          -2.1%     108900        Santa Clara, California
86           6.0%     159000                  Austin, Texas
87          46.4%      37000          Palo Alto, California
88         -15.6%      55524               Moline, Illinois
89           0.3%      78400              Beaverton, Oregon
90          -4.1%      40000          Boston, Massachusetts
91           2.8%       4200                 Houston, Texas
92          14.3%      38018             San Antonio, Texas
93           7.3%      34100        New York City, New York
94          -0.1%      26125             Irvine, California
95          12.9%     117000               Reston, Virginia
96           2.9%      69700               Atlanta, Georgia
97           2.6%      15623        New York City, New York
98          12.2%      34000        New York City, New York
99          32.0%      47000          Indianapolis, Indiana

In [20]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,680985,5.1%,2100000,"Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,637959,11.0%,1556000,"Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,400278,7.7%,400000,"Minnetonka, Minnesota"
3,4,Apple,Technology,391035,2.0%,164000,"Cupertino, California"
4,5,CVS Health,Healthcare,372809,4.2%,259500,"Woonsocket, Rhode Island"
5,6,Berkshire Hathaway,Conglomerate,371433,1.9%,392400,"Omaha, Nebraska"
6,7,Alphabet,Technology and cloud computing,350018,13.9%,183323,"Mountain View, California"
7,8,Exxon Mobil,Petroleum,349595,1.5%,60900,"Spring, Texas"
8,9,McKesson Corporation,Healthcare,308951,11.7%,48000,"Irving, Texas"
9,10,Cencora,Pharmacy wholesale,293959,12.1%,44000,"Conshohocken, Pennsylvania"
10,11,JPMorgan Chase,Financials,278906,16.5%,317233,"New York City, New York"
11,12,Costco Wholesale,Retail,254453,5.0%,333000,"Issaquah, Washington"
12,13,Cigna,Health insurance,247121,26.6%,72398,"Bloomfield, Connecticut"
13,14,Microsoft,Technology and cloud computing,245122,15.7%,228000,"Redmond, Washington"
14,15,Cardinal Health,Healthcare,226827,10.6%,48411,"Dublin, Ohio"
15,16,Chevron,Petroleum,202792,0.9%,45298,"Houston, Texas"
16,17,Bank of America,Financials,192434,11.9%,213193,"Charlotte, North Carolina"
17,18,General Motors,Automotive,187442,9.1%,162000,"Detroit, Michigan"
18,19,Ford Motor,Automotive,184992,5.0%,171000,"Dearborn, Michigan"
19,20,Elevance Health,Healthcare,177011,3.3%,103679,"Indianapolis, Indiana"
20,21,Citigroup,Financials,170757,8.9%,227855,"New York City, New York"
21,22,Meta Platforms,Technology,164501,21.9%,74067,"Menlo Park, California"
22,23,Centene,Healthcare,163071,5.9%,60500,"St. Louis, Missouri"
23,24,The Home Depot,Retail,159514,4.5%,470100,"Atlanta, Georgia"
24,25,Fannie Mae,Financials,152670,8.1%,8200,"Washington, D.C."
25,26,Walgreens Boots Alliance,Pharmaceutical,147658,6.2%,252500,"Deerfield, Illinois"
26,27,Kroger,Retail,147123,-1.9%,409000,"Cincinnati, Ohio"
27,28,Phillips 66,Petroleum,145496,-2.9%,13200,"Houston, Texas"
28,29,Marathon Petroleum,Petroleum,140412,-6.6%,18300,"Findlay, Ohio"
29,30,Verizon Communications,Telecommunications,134788,0.6%,99600,"New York City, New York"
30,31,Nvidia,Technology,130497,114.2%,36000,"Santa Clara, California"
31,32,Goldman Sachs Group,Financials,126853,17.0%,46500,"New York City, New York"
32,33,Wells Fargo,Financials,125397,8.7%,217502,"San Francisco, California"
33,34,Valero Energy,Petroleum,123974,-10.8%,9910,"San Antonio, Texas"
34,35,Comcast,Telecommunications,123731,1.8%,182000,"Philadelphia, Pennsylvania"
35,36,State Farm Insurance,Financials,122951,18.0%,67381,"Bloomington, Illinois"
36,37,AT&T,Conglomerate and telecommunications,122336,-0.1%,140990,"Dallas, Texas"
37,38,Freddie Mac,Financials,122052,13.0%,8090,"McLean, Virginia"
38,39,Humana,Health insurance,117761,10.7%,65680,"Louisville, Kentucky"
39,40,Morgan Stanley,Financials,107285,11.5%,80478,"New York City, New York"
40,41,Target,Retail,106566,-0.8%,440000,"Minneapolis, Minnesota"
41,42,StoneX Group,Financials,99888,64.1%,4500,"New York City, New York"
42,43,Tesla,Automotive and energy,97690,0.9%,125665,"Austin, Texas"
43,44,Dell Technologies,Technology,95567,8.1%,108000,"Round Rock, Texas"
44,45,PepsiCo,Beverage,91854,0.4%,319000,"Purchase, New York"
45,46,Walt Disney,Media,91361,2.8%,205040,"Burbank, California"
46,47,United Parcel Service,Transportation,91070,0.1%,372180,"Atlanta, Georgia"
47,48,Johnson & Johnson,Pharmaceutical,88821,-6.7%,138100,"New Brunswick, New Jersey"
48,49,FedEx,Transportation,87693,-2.7%,422100,"Memphis, Tennessee"
49,50,Archer Daniels Midland,Food industry,85530,-8.9%,43213,"Chicago, Illinois"
50,51,Procter & Gamble,Consumer products manufacturing,84039,2.5%,108000,"Cincinnati, Ohio"
51,52,Lowe's,Retail,83674,-3.1%,215500,"Mooresville, North Carolina"
52,53,Energy Transfer Partners,Petroleum,82671,5.2%,16248,"Dallas, Texas"
53,54,RTX,Aerospace and defense,80739,17.1%,186000,"Arlington County, Virginia"
54,55,Albertsons,Retail,79238,2.0%,196650,"Boise, Idaho"
55,56,Sysco,Food processing,78844,3.3%,76000,"Houston, Texas"
56,57,Progressive,Insurance,75372,21.4%,66308,"Mayfield Village, Ohio"
57,58,American Express,Financials,74201,10.1%,75100,"New York City, New York"
58,59,Lockheed Martin,Aerospace and defense,71043,5.1%,121000,"Bethesda, Maryland"
59,60,MetLife,Financials,70986,6.1%,45000,"New York City, New York"
60,61,HCA Healthcare,Healthcare,70603,8.7%,271000,"Nashville, Tennessee"
61,62,Prudential Financial,Financials,70405,30.4%,37936,"Newark, New Jersey"
62,63,Boeing,Aerospace and defense,66517,-14.5%,172000,"Arlington County, Virginia"
63,64,Caterpillar,Machinery,64809,-3.4%,112900,"Irving, Texas"
64,65,Merck,Pharmaceutical industry,64168,6.7%,74000,"Kenilworth, New Jersey"
65,66,Allstate,Insurance,64106,12.3%,55200,"Northfield Township, Illinois"
66,67,Pfizer,Pharmaceutical industry,63627,8.8%,81000,"New York City, New York"
67,68,IBM,Technology and cloud computing,62753,1.4%,284500,"Armonk, New York"
68,69,New York Life Insurance Company,Insurance,62639,15.3%,15131,"New York City, New York"
69,70,Delta Air Lines,Airline,61643,6.2%,103000,"Atlanta, Georgia"
70,71,Publix Super Markets,Retail,60177,4.6%,255000,"Lakeland, Florida"
71,72,Nationwide Mutual Insurance Company,Financials,58646,7.4%,22453,"Columbus, Ohio"
72,73,TD Synnex,Information Technology,58452,1.6%,25750,"Clearwater, Florida"
73,74,United Airlines Holdings,Airline,57063,6.2%,107300,"Chicago, Illinois"
74,75,ConocoPhillips,Petroleum,56953,-2.8%,11800,"Houston, Texas"
75,76,TJX,Retail,56360,4.0%,364000,"Framingham, Massachusetts"
76,77,AbbVie,Pharmaceutical,56334,3.7%,55000,"Lake Bluff, Illinois"
77,78,Enterprise Products Partners,Petroleum,56219,13.1%,7800,"Houston, Texas"
78,79,Charter Communications,Telecommunications,55085,0.9%,94500,"Stamford, Connecticut"
79,80,Performance Food Group,Food processing,54681,2.5%,36815,"Richmond, Virginia"
80,81,American Airlines Group,Airline,54211,2.7%,133300,"Fort Worth, Texas"
81,82,Capital One Financial,Financials,53938,9.0%,52600,"Tysons, Virginia"
82,83,Cisco Systems,Telecom hardware manufacturing,53803,-5.6%,90400,"San Jose, California"
83,84,HP,Technology,53559,-0.3%,58000,"Palo Alto, California"
84,85,Tyson Foods,Food processing,53309,0.8%,138000,"Springdale, Arkansas"
85,86,Intel,Technology,53101,-2.1%,108900,"Santa Clara, California"
86,87,Oracle,Technology,52961,6.0%,159000,"Austin, Texas"
87,88,Broadcom,Technology,52432,46.4%,37000,"Palo Alto, California"
88,89,Deere,Agriculture manufacturing,51716,-15.6%,55524,"Moline, Illinois"
89,90,Nike,Apparel,51361,0.3%,78400,"Beaverton, Oregon"
90,91,Liberty Mutual Insurance Group,Insurance,50429,-4.1%,40000,"Boston, Massachusetts"
91,92,Plains GP Holdings,Petroleum,50073,2.8%,4200,"Houston, Texas"
92,93,USAA,Insurance,48560,14.3%,38018,"San Antonio, Texas"
93,94,Bristol-Myers Squibb,Pharmaceutical,48300,7.3%,34100,"New York City, New York"
94,95,Ingram Micro Holding,Technology,47984,-0.1%,26125,"Irvine, California"
95,96,General Dynamics,Aerospace and defense,47716,12.9%,117000,"Reston, Virginia"
96,97,Coca-Cola,Beverage,47061,2.9%,69700,"Atlanta, Georgia"
97,98,TIAA,Financials,46946,2.6%,15623,"New York City, New York"
98,99,Travelers,Insurance,46423,12.2%,34000,"New York City, New York"
99,100,Eli Lilly,Pharmaceutical,45043,32.0%,47000,"Indianapolis, Indiana"

In [29]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

table = soup.select_one("table.wikitable")

print("Table found:", table is not None)

df = pd.read_html(StringIO(str(table)))[0]

pd.set_option("display.max_rows", 100)

print(df)

Table found: True
   Ranks                                     Name  \
   Ranks                                     Name
0      1                                   Amazon
1      2                                  Walmart
2      3          State Grid Corporation of China
3      4                             Saudi Aramco
4      5     China National Petroleum Corporation
5      6          China Petrochemical Corporation
6      7                                    Apple
7      8                                 Alphabet
8      9                       UnitedHealth Group
9     10                       Berkshire Hathaway
10    11                               CVS Health
11    12                         Volkswagen Group
12    13                               ExxonMobil
13    14                                    Vitol
14    15                                    Shell
15    16     China State Construction Engineering
16    17                                   Toyota
17    18                                 McKesson
18    19                                Microsoft
19    20                                  Cencora
20    21                                Trafigura
21    22                                   Costco
22    23                           JPMorgan Chase
23    24  Industrial and Commercial Bank of China
24    25                           Schwarz Gruppe
25    26                            TotalEnergies
26    27                                 Glencore
27    28                                   Nvidia
28    29                                       BP
29    30                          Cardinal Health
30    31                               Stellantis
31    32                                  Chevron
32    33                  China Construction Bank
33    34                      Samsung Electronics
34    35                                  Foxconn
35    36                                    Cigna
36    37               Agricultural Bank of China
37    38    China Railway Engineering Corporation
38    39                                  Cargill
39    40                       Ford Motor Company
40    41                            Bank of China
41    42                          Bank of America
42    43                           General Motors
43    44                          Elevance Health
44    45                                BMW Group
45    46                      Mercedes-Benz Group
46    47                           Meta Platforms
47    48   China Railway Construction Corporation
48    49                                    Baowu
49    50                                Citigroup

                          Industry           Revenue            Profit  \
                          Industry USD (in billions) USD (in billions)
0   Retail  Information technology               716             79.90
1                           Retail               713             21.80
2                      Electricity               545              9.20
3                      Oil and gas               480            106.00
4                      Oil and gas               476             25.20
5                      Oil and gas               429              9.30
6           Information technology               416            112.00
7           Information technology               402            132.00
8                       Healthcare               400             14.40
9                       Financials               371             88.90
10                      Healthcare               357              8.30
11                      Automotive               348             17.90
12                     Oil and gas               344             36.00
13                     Commodities               331             13.00
14                     Oil and gas               323             19.30
15                    Construction               320              4.20
16                      Automotive               312             34.20
17                      Healthcare               308              3.00
18          Information technology               281            101.00
19                      Healthcare               262              1.70
20                     Commodities               244              7.30
21                          Retail               242              6.20
22                      Financials               239             49.50
23                      Financials               222             51.40
24                          Retail               220               NaN
25                     Oil and gas               218             21.30
26                     Commodities               217              4.20
27                  Semiconductors               215            120.00
28                     Oil and gas               213             15.20
29                      Healthcare               205              0.26
30                      Automotive               204             20.10
31                     Oil and gas               200             21.30
32                      Financials               199             46.90
33                     Electronics               198             11.00
34                     Electronics               197              4.50
35                      Healthcare               195              5.10
36                      Financials               192             38.00
37                    Construction               178              2.10
38                    Conglomerate               177             17.60
39                      Automotive               176              4.30
40                      Financials               172             32.70
41                      Financials               171             26.50
42                      Automotive               171             10.10
43                      Healthcare               171              5.90
44                      Automotive               168             12.20
45                      Automotive               165             15.40
46                    Social media               164             62.30
47                    Construction               160              1.70
48                           Steel               157              2.40
49                      Financials               156              9.20

   Employees Headquarters[note 1] State-owned      Ref.
   Employees Headquarters[note 1] State-owned      Ref.
0    1576000        United States         NaN       [5]
1    2100000        United States         NaN       [6]
2    1361423                China         NaN       [7]
3      73311         Saudi Arabia         NaN       [8]
4    1026301                China         NaN       [9]
5     513434                China         NaN      [10]
6     166000        United States         NaN      [11]
7     190820        United States         NaN      [12]
8     400000        United States         NaN      [13]
9     392400        United States         NaN      [14]
10    259500        United States         NaN      [15]
11    684025              Germany         NaN      [16]
12     61500        United States         NaN      [17]
13      1560          Switzerland         NaN  [18][19]
14    103000       United Kingdom         NaN      [20]
15    382894                China         NaN      [21]
16    380793                Japan         NaN      [22]
17     48000        United States         NaN      [23]
18    228000        United States         NaN      [24]
19     44000        United States         NaN      [25]
20     12479            Singapore         NaN      [26]
21    316000        United States         NaN      [27]
22    309926        United States         NaN      [28]
23    419252                China         NaN      [29]
24    604000              Germany         NaN      [30]
25    102579               France         NaN      [31]
26     83426          Switzerland         NaN      [32]
27     36000        United States         NaN      [33]
28     79400       United Kingdom         NaN      [34]
29     47520        United States         NaN      [35]
30    258275          Netherlands         NaN      [36]
31     45600        United States         NaN      [37]
32    376871                China         NaN      [38]
33    267860          South Korea         NaN      [39]
34    621393               Taiwan         NaN      [40]
35     71413        United States         NaN      [41]
36    451003                China         NaN      [42]
37    314149                China         NaN      [43]
38    160000        United States         NaN      [44]
39    177000        United States         NaN      [45]
40    306931                China         NaN      [46]
41    212985        United States         NaN      [47]
42    163000        United States         NaN      [48]
43    104900        United States         NaN      [49]
44    154950              Germany         NaN      [50]
45    166056              Germany         NaN      [51]
46     78450        United States         NaN      [52]
47    336433                China         NaN      [53]
48    258697                China         NaN      [54]
49    237925        United States         NaN      [55]

In [28]:
df

,Ranks,Name,Industry,Revenue,Profit,Employees,Headquarters[note 1],State-owned,Ref.
,Ranks,Name,Industry,USD (in billions),USD (in billions),Employees,Headquarters[note 1],State-owned,Ref.
0,1,Amazon,Retail Information technology,716,79.90,1576000,United States,NaN,[5]
1,2,Walmart,Retail,713,21.80,2100000,United States,NaN,[6]
2,3,State Grid Corporation of China,Electricity,545,9.20,1361423,China,NaN,[7]
3,4,Saudi Aramco,Oil and gas,480,106.00,73311,Saudi Arabia,NaN,[8]
4,5,China National Petroleum Corporation,Oil and gas,476,25.20,1026301,China,NaN,[9]
5,6,China Petrochemical Corporation,Oil and gas,429,9.30,513434,China,NaN,[10]
6,7,Apple,Information technology,416,112.00,166000,United States,NaN,[11]
7,8,Alphabet,Information technology,402,132.00,190820,United States,NaN,[12]
8,9,UnitedHealth Group,Healthcare,400,14.40,400000,United States,NaN,[13]
9,10,Berkshire Hathaway,Financials,371,88.90,392400,United States,NaN,[14]
10,11,CVS Health,Healthcare,357,8.30,259500,United States,NaN,[15]
11,12,Volkswagen Group,Automotive,348,17.90,684025,Germany,NaN,[16]
12,13,ExxonMobil,Oil and gas,344,36.00,61500,United States,NaN,[17]
13,14,Vitol,Commodities,331,13.00,1560,Switzerland,NaN,[18][19]
14,15,Shell,Oil and gas,323,19.30,103000,United Kingdom,NaN,[20]
15,16,China State Construction Engineering,Construction,320,4.20,382894,China,NaN,[21]
16,17,Toyota,Automotive,312,34.20,380793,Japan,NaN,[22]
17,18,McKesson,Healthcare,308,3.00,48000,United States,NaN,[23]
18,19,Microsoft,Information technology,281,101.00,228000,United States,NaN,[24]
19,20,Cencora,Healthcare,262,1.70,44000,United States,NaN,[25]
20,21,Trafigura,Commodities,244,7.30,12479,Singapore,NaN,[26]
21,22,Costco,Retail,242,6.20,316000,United States,NaN,[27]
22,23,JPMorgan Chase,Financials,239,49.50,309926,United States,NaN,[28]
23,24,Industrial and Commercial Bank of China,Financials,222,51.40,419252,China,NaN,[29]
24,25,Schwarz Gruppe,Retail,220,NaN,604000,Germany,NaN,[30]
25,26,TotalEnergies,Oil and gas,218,21.30,102579,France,NaN,[31]
26,27,Glencore,Commodities,217,4.20,83426,Switzerland,NaN,[32]
27,28,Nvidia,Semiconductors,215,120.00,36000,United States,NaN,[33]
28,29,BP,Oil and gas,213,15.20,79400,United Kingdom,NaN,[34]
29,30,Cardinal Health,Healthcare,205,0.26,47520,United States,NaN,[35]
30,31,Stellantis,Automotive,204,20.10,258275,Netherlands,NaN,[36]
31,32,Chevron,Oil and gas,200,21.30,45600,United States,NaN,[37]
32,33,China Construction Bank,Financials,199,46.90,376871,China,NaN,[38]
33,34,Samsung Electronics,Electronics,198,11.00,267860,South Korea,NaN,[39]
34,35,Foxconn,Electronics,197,4.50,621393,Taiwan,NaN,[40]
35,36,Cigna,Healthcare,195,5.10,71413,United States,NaN,[41]
36,37,Agricultural Bank of China,Financials,192,38.00,451003,China,NaN,[42]
37,38,China Railway Engineering Corporation,Construction,178,2.10,314149,China,NaN,[43]
38,39,Cargill,Conglomerate,177,17.60,160000,United States,NaN,[44]
39,40,Ford Motor Company,Automotive,176,4.30,177000,United States,NaN,[45]
40,41,Bank of China,Financials,172,32.70,306931,China,NaN,[46]
41,42,Bank of America,Financials,171,26.50,212985,United States,NaN,[47]
42,43,General Motors,Automotive,171,10.10,163000,United States,NaN,[48]
43,44,Elevance Health,Healthcare,171,5.90,104900,United States,NaN,[49]
44,45,BMW Group,Automotive,168,12.20,154950,Germany,NaN,[50]
45,46,Mercedes-Benz Group,Automotive,165,15.40,166056,Germany,NaN,[51]
46,47,Meta Platforms,Social media,164,62.30,78450,United States,NaN,[52]
47,48,China Railway Construction Corporation,Construction,160,1.70,336433,China,NaN,[53]
48,49,Baowu,Steel,157,2.40,258697,China,NaN,[54]
49,50,Citigroup,Financials,156,9.20,237925,United States,NaN,[55]

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_largest_manufacturing_companies_by_revenue"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

table = soup.select_one("table.wikitable")

print("Table found:", table is not None)

df = pd.read_html(StringIO(str(table)))[0]

pd.set_option("display.max_rows", 50)

print(df)

Table found: True
    No.                               Company  \
0     1                                 Apple
1     2                            Volkswagen
2     3                                Toyota
3     4                   Samsung Electronics
4     5  Hon Hai Precision Industry (Foxconn)
5     6                        General Motors
6     7                            Ford Motor
7     8                            Stellantis
8     9   China Railway and Engineering Group
9    10                   Mercedes-Benz Group
10   11                                   BMW
11   12                           Honda Motor
12   13                                Nvidia
13   14                         Hyundai Motor
14   15               China Baowu Steel Group
15   16                            Mitsubishi
16   17                          Hengli Group
17   18                                Huawei
18   19                       China Minmetals
19   20                                   BYD
20   21                                Nestle
21   22                                 Bosch
22   23                                 Tesla
23   24                     Dell Technologies
24   25                               PepsiCo
25   26                        Christian Dior
26   27      Zhejiang Rongsheng Holding Group
27   28                                  TSMC
28   29                     Johnson & Johnson
29   30                           COFCO Group
30   31                            SAIC Motor
31   32                Archer Daniels Midland
32   33                               Siemens
33   34                                  Sony
34   35                      Procter & Gamble
35   36                  Wuchan Zhongda Group
36   37                          Nissan Motor
37   38                       RTX Corporation
38   39          Zhejiang Geely Holding Group
39   40                                   Kia
40   41               Shenghong Holding Group
41   42                             FAW Group
42   43                        Jiangxi Copper
43   44     Shandong Weiqiao Pioneering Group
44   45                              JBS N.V.
45   46                                Airbus
46   47                       Lockheed Martin
47   48                           Roche Group
48   49                                  BASF
49   50                                Lenovo

                                     Industry  Revenue (in billion US$)  \
0                                 Electronics                   391.035
1                                  Automotive                   351.093
2                                  Automotive                   315.110
3                                 Electronics                   220.637
4                                 Electronics                   213.699
5                                  Automotive                   187.442
6                                  Automotive                   184.992
7                                  Automotive                   169.653
8                                 Engineering                   161.337
9                                  Automotive                   157.450
10                                 Automotive                   153.974
11                                 Automotive                   142.274
12                    Semiconductors, various                   130.497
13                                 Automotive                   128.502
14                                     Metals                   125.113
15                       Engineering, various                   122.127
16                 Chemicals, oils, polyester                   121.126
17  Telecommunications equipment, electronics                   119.813
18                                     Metals                   115.806
19                    Automotive, electronics                   108.004
20                           Food & beverages                   103.750
21                       Engineering, various                    97.702
22                        Automotive, various                    97.690
23                                Electronics                    95.567
24                           Food & beverages                    91.854
25                               Luxury goods                    91.579
26                 Chemicals, oils, polyester                    91.534
27                             Semiconductors                    90.167
28                            Pharmaceuticals                    88.821
29                           Food & beverages                    88.260
30                                 Automotive                    87.224
31                           Food & beverages                    85.530
32                                Engineering                    85.433
33                                Electronics                    85.000
34                             Consumer goods                    84.039
35                     Tire & rubber, various                    84.039
36                                 Automotive                    82.871
37                        Aerospace & defense                    80.738
38                                 Automotive                    79.891
39                                 Automotive                    78.795
40                 Chemicals, oils, polyester                    78.612
41                                 Automotive                    77.737
42                                     Metals                    77.668
43               Textiles, metals, automotive                    77.626
44                           Food & beverages                    77.183
45                        Aerospace & defense                    74.688
46                        Aerospace & defense                    71.043
47                            Pharmaceuticals                    70.861
48                                  Chemicals                    70.574
49                                Electronics                    69.077

     Headquarters
0   United States
1         Germany
2           Japan
3     South Korea
4          Taiwan
5   United States
6   United States
7     Netherlands
8           China
9         Germany
10        Germany
11          Japan
12  United States
13    South Korea
14          China
15          Japan
16          China
17          China
18          China
19          China
20    Switzerland
21        Germany
22  United States
23  United States
24  United States
25         France
26          China
27         Taiwan
28  United States
29          China
30          China
31  United States
32        Germany
33          Japan
34  United States
35          China
36          Japan
37  United States
38          China
39    South Korea
40          China
41          China
42          China
43          China
44         Brazil
45         France
46  United States
47    Switzerland
48        Germany
49      Hong Kong

In [36]:
df

,No.,Company,Industry,Revenue (in billion US$),Headquarters
0,1,Apple,Electronics,391.035,United States
1,2,Volkswagen,Automotive,351.093,Germany
2,3,Toyota,Automotive,315.110,Japan
3,4,Samsung Electronics,Electronics,220.637,South Korea
4,5,Hon Hai Precision Industry (Foxconn),Electronics,213.699,Taiwan
5,6,General Motors,Automotive,187.442,United States
6,7,Ford Motor,Automotive,184.992,United States
7,8,Stellantis,Automotive,169.653,Netherlands
8,9,China Railway and Engineering Group,Engineering,161.337,China
9,10,Mercedes-Benz Group,Automotive,157.450,Germany
10,11,BMW,Automotive,153.974,Germany
11,12,Honda Motor,Automotive,142.274,Japan
12,13,Nvidia,"Semiconductors, various",130.497,United States
13,14,Hyundai Motor,Automotive,128.502,South Korea
14,15,China Baowu Steel Group,Metals,125.113,China
15,16,Mitsubishi,"Engineering, various",122.127,Japan
16,17,Hengli Group,"Chemicals, oils, polyester",121.126,China
17,18,Huawei,"Telecommunications equipment, electronics",119.813,China
18,19,China Minmetals,Metals,115.806,China
19,20,BYD,"Automotive, electronics",108.004,China
20,21,Nestle,Food & beverages,103.750,Switzerland
21,22,Bosch,"Engineering, various",97.702,Germany
22,23,Tesla,"Automotive, various",97.690,United States
23,24,Dell Technologies,Electronics,95.567,United States
24,25,PepsiCo,Food & beverages,91.854,United States
25,26,Christian Dior,Luxury goods,91.579,France
26,27,Zhejiang Rongsheng Holding Group,"Chemicals, oils, polyester",91.534,China
27,28,TSMC,Semiconductors,90.167,Taiwan
28,29,Johnson & Johnson,Pharmaceuticals,88.821,United States
29,30,COFCO Group,Food & beverages,88.260,China
30,31,SAIC Motor,Automotive,87.224,China
31,32,Archer Daniels Midland,Food & beverages,85.530,United States
32,33,Siemens,Engineering,85.433,Germany
33,34,Sony,Electronics,85.000,Japan
34,35,Procter & Gamble,Consumer goods,84.039,United States
35,36,Wuchan Zhongda Group,"Tire & rubber, various",84.039,China
36,37,Nissan Motor,Automotive,82.871,Japan
37,38,RTX Corporation,Aerospace & defense,80.738,United States
38,39,Zhejiang Geely Holding Group,Automotive,79.891,China
39,40,Kia,Automotive,78.795,South Korea
40,41,Shenghong Holding Group,"Chemicals, oils, polyester",78.612,China
41,42,FAW Group,Automotive,77.737,China
42,43,Jiangxi Copper,Metals,77.668,China
43,44,Shandong Weiqiao Pioneering Group,"Textiles, metals, automotive",77.626,China
44,45,JBS N.V.,Food & beverages,77.183,Brazil
45,46,Airbus,Aerospace & defense,74.688,France
46,47,Lockheed Martin,Aerospace & defense,71.043,United States
47,48,Roche Group,Pharmaceuticals,70.861,Switzerland
48,49,BASF,Chemicals,70.574,Germany
49,50,Lenovo,Electronics,69.077,Hong Kong

In [2]:
import requests
import pandas as pd
from io import StringIO
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/List_of_largest_biomedical_companies_by_market_capitalization"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

table = soup.select_one("table.wikitable")

print("Table found:", table is not None)

df = pd.read_html(StringIO(str(table)))[0]

pd.set_option("display.max_rows", 50)

print(df)

Table found: True
    Rank   Chg                       Company   Country       Traded on  \
0      1   NaN          Johnson & Johnson[P]       USA       NYSE: JNJ
1      2   1.0                      Roche[P]       SUI        SIX: ROG
2      3   2.0                     Pfizer[P]       USA       NYSE: PFE
3      4   1.0                   Novartis[P]       SUI       NYSE: NVS
4      5   1.0                Merck & Co.[P]       USA       NYSE: MRK
5      6   NaN                    Moderna[P]       USA    NSE: MRNA[1]
6      7   NaN        Abbott Laboratories[P]       USA       NYSE: ABT
7      8   2.0                     AbbVie[B]       USA      NYSE: ABBV
8      9   NaN               Novo Nordisk[P]       DEN       NYSE: NVO
9     10   2.0             Eli Lilly & Co[P]       USA       NYSE: LLY
10    11   3.0       Bristol-Myers Squibb[P]       USA     Nasdaq: BMY
11    12   4.0                      Amgen[B]       USA    Nasdaq: AMGN
12    13   2.0                AstraZeneca[P]  GBR  SWE        LSE: AZN
13    14   4.0                     Sanofi[P]       FRA       NYSE: SNY
14    15   2.0            GlaxoSmithKline[P]       GBR        LSE: GSK
15    16   1.0        Stryker Corporation[P]       USA       NYSE: SYK
16    17   2.0                     Zoetis[P]       USA     Nasdaq: ZTS
17    18   3.0            Gilead Sciences[B]       USA    Nasdaq: GILD
18    19   6.0             Daiichi Sankyo[P]       JPN   Nasdaq: DSNKY
19    20   1.0     Vertex Pharmaceuticals[B]       USA    Nasdaq: VRTX
20    21   4.0                      Bayer[P]       GER       FWB: BAYN
21    22   2.0      Takeda Pharmaceutical[P]       JPN     Nasdaq: TAK
22    23   1.0                   Illumina[B]       USA    Nasdaq: ILMN
23    24   2.0  Regeneron Pharmaceuticals[B]       USA    Nasdaq: REGN
24    25   3.0                     Biogen[B]       USA    Nasdaq: BIIB
25    26   2.0    Alexion Pharmaceuticals[P]       USA    Nasdaq: ALXN
26    27   3.0                     Seagen[B]       USA    Nasdaq: SGEN
27    28   1.0                   Astellas[P]       JPN       TYO: 4503
28    29   4.0                     Genmab[B]       DEN    Nasdaq: GMAB
29    30   1.0       Eisai Pharmaceutical[P]       JPN       TYO: 4523
30    31   NaN   Alnylam Pharmaceuticals [P]       USA    NSE: ALNY[6]
31    32   NaN                     Incyte[P]       USA       NSE: INCY
32    33   NaN                   BioMarin[P]       USA       NSE: BMRN
33    34   NaN                   BeiGene [P]       CHN     SSE: 688235
34    35   1.0                   BioNTech[P]       GER       NSE: BNTX
35    36   1.0       Horizon Therapeutics[P]       USA       NSE: HZNP
36    37   1.0            10x Genomics[7][P]       USA        NSE: TXG
37    38   1.0   Jiangsu Hengrui Medicine[P]       CHN     SSE: 600276
38    39   1.0                     Elanco[P]       USA      NYSE: ELAN
39    40   1.0                  Celltrion[P]       ROK     KRX: 068270
40    41   1.0                    Viatris[P]       USA       NSE: VTRS
41    42   1.0                 Sun Pharma[P]       IND  NSE: SUNPHARMA
42    43   1.0        Divi's Laboratories[P]       IND   NSE: DIVISLAB
43    44   1.0   Dr. Reddy's Laboratories[P]       IND    NSE: DRREDDY
44    45  31.0      Teva Pharmaceuticals [P]       ISR      NYSE: TEVA
45    46   1.0                      Cipla[P]       IND      NSE: CIPLA

             Largest  2020[1]    2019    2018    2017  2016[2][3]  2015[4]  \
0   399.9 (Dec 2020)   399.99  385.00  346.10  375.40      314.10   284.20
1   291.1 (Dec 2020)   291.12  281.10  209.30  216.70      192.10   234.70
2   310.5 (Jul 2000)   208.11  216.70  259.70  215.90      196.30   199.30
3   275.2 (Jul 2015)   202.09  240.00  200.00  196.70      170.50   206.10
4   232.9 (Dec 2019)   201.80  232.90  205.80  153.30      164.30   147.60
5     201 (Sep 2021)    68.50   45.00     NaN     NaN         NaN      NaN
6   190.4 (Dec 2020)   190.44  153.50  126.80   99.30       56.40    67.00
7   196.2 (Jan 2018)   182.27  130.90  146.30  154.40      100.20    96.80
8   161.9 (Dec 2020)   161.99  137.10  111.90  131.20       92.60   153.90
9   158.3 (Dec 2020)   158.30  126.90  125.60   93.00       80.90    93.40
10  137.8 (Dec 2020)   137.85  105.00   85.00  100.30       98.20   114.80
11  145.8 (Dec 2019)   129.79  144.60  128.80  126.20      108.90   122.50
12  130.8 (Dec 2019)   129.44  130.80   96.20   87.90       68.80    85.80
13  151.3 (Sep 2014)   120.66   63.50  108.40  108.20      101.80   111.80
14  174.9 (May 2006)    90.15  117.20   94.80   87.90       93.30    97.60
15   88.8 (Dec 2020)    88.81   78.50   58.60   58.00       45.10    34.70
16   76.6 (Aug 2020)    75.97   63.20   41.40   35.10       26.40    23.80
17  179.6 (Jun 2013)    71.93   82.30   81.60   93.60       96.60   145.80
18   45.3 (Dec 2019)    63.92   45.30   22.70   27.50       35.30    38.80
19   78.9 (Jul 2020)    61.33   56.30   42.20   37.90       18.30    31.00
20  129.0 (Mar 2015)    58.12   80.10   63.10  101.90       85.30   103.20
21   61.5 (Dec 2019)    56.78   61.50   52.90   40.20       45.60    47.80
22   56.0 (Jul 2019)    53.51   48.20   44.10   40.20       39.40    35.40
23   61.4 (Aug 2015)    52.52   41.20   40.30   40.40       39.30    56.50
24  111.7 (Mar 2015)    38.66   54.70   63.50   67.40       61.60    68.30
25   47.0 (Jul 2015)    33.52   24.30   21.70   26.70       27.40    43.10
26   38.2 (Oct 2020)    34.44   19.50   13.80     NaN         NaN      NaN
27   40.6 (Dec 2015)    27.52   32.70   23.80   29.30       25.70    40.60
28   25.9 (Nov 2020)    25.53   14.50   10.60   10.80       10.80     8.80
29   37.3 (Dec 2016)    19.93   21.50   23.00   24.50       37.30    28.80
30             23.36    18.50   24.00   21.00   16.00         NaN      NaN
31   31.2 (Mar 2017)    19.25   18.80   13.50   18.30       15.40    10.60
32   24.0 (Jul 2015)    16.03   15.20   15.10   18.30       20.40    13.80
33  33.14 (Nov 2021)    34.20   27.00   26.00   24.03       10.28     8.33
34             44.07    62.52   19.62    7.68     NaN         NaN      NaN
35  18.06 (Dec 2020)    14.20   11.60    9.30    5.00        6.50     2.80
36             17.54    11.20     NaN     NaN     NaN         NaN      NaN
37             41.17    59.98   93.42   60.85   30.53       30.54    16.79
38  13.06 (Nov 2020)    11.20     NaN     NaN     NaN         NaN      NaN
39      23.03 (2021)    40.90   19.22     NaN     NaN         NaN      NaN
40  18.50 (Dec 2021)      NaN     NaN     NaN     NaN         NaN      NaN
41      27.15 (2021)    19.01     NaN     NaN     NaN         NaN      NaN
42  15.29 (Nov 2021)      NaN     NaN     NaN     NaN         NaN      NaN
43      10.94 (2021)    11.75     NaN     NaN     NaN         NaN      NaN
44  110.5 (Jul 2015)    10.69   48.30   16.20   24.40       32.70    13.20
45  10.21 (Dec 2021)    10.19     NaN     NaN     NaN         NaN      NaN

    2014[5]   2013
0    277.80  258.3
1    258.50  240.3
2    205.40  196.0
3    229.80  195.0
4    166.90  146.5
5       NaN      -
6     67.90   59.3
7    104.10   83.8
8    125.40      -
9     76.60   57.0
10    97.60   87.2
11    93.10   78.7
12    88.90   74.6
13   138.10  142.0
14   128.90  129.6
15    35.70   28.4
16    21.60   16.3
17   109.00   78.4
18    33.20   28.7
19    28.70   17.4
20   113.20  117.4
21    37.50   34.3
22    28.60   25.7
23    42.00   27.4
24    79.70   66.1
25    36.70   26.0
26      NaN    NaN
27    35.80   27.6
28     3.80    2.6
29    30.20   28.7
30      NaN      -
31     7.30    4.6
32    12.90   10.8
33     4.45   1.20
34      NaN      -
35     2.00      -
36      NaN      -
37    15.10      -
38      NaN      -
39      NaN      -
40      NaN      -
41      NaN      -
42      NaN      -
43      NaN      -
44    70.50   29.3
45      NaN      -

In [3]:
df

,Rank,Chg,Company,Country,Traded on,Largest,2020[1],2019,2018,2017,2016[2][3],2015[4],2014[5],2013
0,1,NaN,Johnson & Johnson[P],USA,NYSE: JNJ,399.9 (Dec 2020),399.99,385.00,346.10,375.40,314.10,284.20,277.80,258.3
1,2,1.0,Roche[P],SUI,SIX: ROG,291.1 (Dec 2020),291.12,281.10,209.30,216.70,192.10,234.70,258.50,240.3
2,3,2.0,Pfizer[P],USA,NYSE: PFE,310.5 (Jul 2000),208.11,216.70,259.70,215.90,196.30,199.30,205.40,196.0
3,4,1.0,Novartis[P],SUI,NYSE: NVS,275.2 (Jul 2015),202.09,240.00,200.00,196.70,170.50,206.10,229.80,195.0
4,5,1.0,Merck & Co.[P],USA,NYSE: MRK,232.9 (Dec 2019),201.80,232.90,205.80,153.30,164.30,147.60,166.90,146.5
5,6,NaN,Moderna[P],USA,NSE: MRNA[1],201 (Sep 2021),68.50,45.00,NaN,NaN,NaN,NaN,NaN,-
6,7,NaN,Abbott Laboratories[P],USA,NYSE: ABT,190.4 (Dec 2020),190.44,153.50,126.80,99.30,56.40,67.00,67.90,59.3
7,8,2.0,AbbVie[B],USA,NYSE: ABBV,196.2 (Jan 2018),182.27,130.90,146.30,154.40,100.20,96.80,104.10,83.8
8,9,NaN,Novo Nordisk[P],DEN,NYSE: NVO,161.9 (Dec 2020),161.99,137.10,111.90,131.20,92.60,153.90,125.40,-
9,10,2.0,Eli Lilly & Co[P],USA,NYSE: LLY,158.3 (Dec 2020),158.30,126.90,125.60,93.00,80.90,93.40,76.60,57.0
10,11,3.0,Bristol-Myers Squibb[P],USA,Nasdaq: BMY,137.8 (Dec 2020),137.85,105.00,85.00,100.30,98.20,114.80,97.60,87.2
11,12,4.0,Amgen[B],USA,Nasdaq: AMGN,145.8 (Dec 2019),129.79,144.60,128.80,126.20,108.90,122.50,93.10,78.7
12,13,2.0,AstraZeneca[P],GBR SWE,LSE: AZN,130.8 (Dec 2019),129.44,130.80,96.20,87.90,68.80,85.80,88.90,74.6
13,14,4.0,Sanofi[P],FRA,NYSE: SNY,151.3 (Sep 2014),120.66,63.50,108.40,108.20,101.80,111.80,138.10,142.0
14,15,2.0,GlaxoSmithKline[P],GBR,LSE: GSK,174.9 (May 2006),90.15,117.20,94.80,87.90,93.30,97.60,128.90,129.6
15,16,1.0,Stryker Corporation[P],USA,NYSE: SYK,88.8 (Dec 2020),88.81,78.50,58.60,58.00,45.10,34.70,35.70,28.4
16,17,2.0,Zoetis[P],USA,Nasdaq: ZTS,76.6 (Aug 2020),75.97,63.20,41.40,35.10,26.40,23.80,21.60,16.3
17,18,3.0,Gilead Sciences[B],USA,Nasdaq: GILD,179.6 (Jun 2013),71.93,82.30,81.60,93.60,96.60,145.80,109.00,78.4
18,19,6.0,Daiichi Sankyo[P],JPN,Nasdaq: DSNKY,45.3 (Dec 2019),63.92,45.30,22.70,27.50,35.30,38.80,33.20,28.7
19,20,1.0,Vertex Pharmaceuticals[B],USA,Nasdaq: VRTX,78.9 (Jul 2020),61.33,56.30,42.20,37.90,18.30,31.00,28.70,17.4
20,21,4.0,Bayer[P],GER,FWB: BAYN,129.0 (Mar 2015),58.12,80.10,63.10,101.90,85.30,103.20,113.20,117.4
21,22,2.0,Takeda Pharmaceutical[P],JPN,Nasdaq: TAK,61.5 (Dec 2019),56.78,61.50,52.90,40.20,45.60,47.80,37.50,34.3
22,23,1.0,Illumina[B],USA,Nasdaq: ILMN,56.0 (Jul 2019),53.51,48.20,44.10,40.20,39.40,35.40,28.60,25.7
23,24,2.0,Regeneron Pharmaceuticals[B],USA,Nasdaq: REGN,61.4 (Aug 2015),52.52,41.20,40.30,40.40,39.30,56.50,42.00,27.4
24,25,3.0,Biogen[B],USA,Nasdaq: BIIB,111.7 (Mar 2015),38.66,54.70,63.50,67.40,61.60,68.30,79.70,66.1
25,26,2.0,Alexion Pharmaceuticals[P],USA,Nasdaq: ALXN,47.0 (Jul 2015),33.52,24.30,21.70,26.70,27.40,43.10,36.70,26.0
26,27,3.0,Seagen[B],USA,Nasdaq: SGEN,38.2 (Oct 2020),34.44,19.50,13.80,NaN,NaN,NaN,NaN,NaN
27,28,1.0,Astellas[P],JPN,TYO: 4503,40.6 (Dec 2015),27.52,32.70,23.80,29.30,25.70,40.60,35.80,27.6
28,29,4.0,Genmab[B],DEN,Nasdaq: GMAB,25.9 (Nov 2020),25.53,14.50,10.60,10.80,10.80,8.80,3.80,2.6
29,30,1.0,Eisai Pharmaceutical[P],JPN,TYO: 4523,37.3 (Dec 2016),19.93,21.50,23.00,24.50,37.30,28.80,30.20,28.7
30,31,NaN,Alnylam Pharmaceuticals [P],USA,NSE: ALNY[6],23.36,18.50,24.00,21.00,16.00,NaN,NaN,NaN,-
31,32,NaN,Incyte[P],USA,NSE: INCY,31.2 (Mar 2017),19.25,18.80,13.50,18.30,15.40,10.60,7.30,4.6
32,33,NaN,BioMarin[P],USA,NSE: BMRN,24.0 (Jul 2015),16.03,15.20,15.10,18.30,20.40,13.80,12.90,10.8
33,34,NaN,BeiGene [P],CHN,SSE: 688235,33.14 (Nov 2021),34.20,27.00,26.00,24.03,10.28,8.33,4.45,1.20
34,35,1.0,BioNTech[P],GER,NSE: BNTX,44.07,62.52,19.62,7.68,NaN,NaN,NaN,NaN,-
35,36,1.0,Horizon Therapeutics[P],USA,NSE: HZNP,18.06 (Dec 2020),14.20,11.60,9.30,5.00,6.50,2.80,2.00,-
36,37,1.0,10x Genomics[7][P],USA,NSE: TXG,17.54,11.20,NaN,NaN,NaN,NaN,NaN,NaN,-
37,38,1.0,Jiangsu Hengrui Medicine[P],CHN,SSE: 600276,41.17,59.98,93.42,60.85,30.53,30.54,16.79,15.10,-
38,39,1.0,Elanco[P],USA,NYSE: ELAN,13.06 (Nov 2020),11.20,NaN,NaN,NaN,NaN,NaN,NaN,-
39,40,1.0,Celltrion[P],ROK,KRX: 068270,23.03 (2021),40.90,19.22,NaN,NaN,NaN,NaN,NaN,-
40,41,1.0,Viatris[P],USA,NSE: VTRS,18.50 (Dec 2021),NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
41,42,1.0,Sun Pharma[P],IND,NSE: SUNPHARMA,27.15 (2021),19.01,NaN,NaN,NaN,NaN,NaN,NaN,-
42,43,1.0,Divi's Laboratories[P],IND,NSE: DIVISLAB,15.29 (Nov 2021),NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
43,44,1.0,Dr. Reddy's Laboratories[P],IND,NSE: DRREDDY,10.94 (2021),11.75,NaN,NaN,NaN,NaN,NaN,NaN,-
44,45,31.0,Teva Pharmaceuticals [P],ISR,NYSE: TEVA,110.5 (Jul 2015),10.69,48.30,16.20,24.40,32.70,13.20,70.50,29.3
45,46,1.0,Cipla[P],IND,NSE: CIPLA,10.21 (Dec 2021),10.19,NaN,NaN,NaN,NaN,NaN,NaN,-