In [1]:
import pandas as pd
import numpy as np

In [9]:
#creating an array

komal=np.array([[46,58],[66,70],[57,89],[86,91]])

In [12]:
#creating a dataframe
df=pd.DataFrame(komal,index=['row1','row2','row3','row4'],
                columns=['col1','col2'])

In [13]:
df

      col1  col2
row1    46    58
row2    66    70
row3    57    89
row4    86    91

In [14]:
komal=[[46,58],[66,70],[57,89],[86,91]]

In [16]:
df=pd.DataFrame(komal,index=['row1','row2','row3','row4'],
                columns=['col1','col2'])

In [17]:
df

      col1  col2
row1    46    58
row2    66    70
row3    57    89
row4    86    91

In [6]:
import pandas as pd
import numpy as np

In [11]:
#by dictionery

states=["maharashtra","gujarat","tamilnadu","karnataka"]
districts=["nagpur", "surat", "coimbatur", "banglore"]

In [12]:
dict_states={
    "states":states,
    "districts":districts,
    }

In [15]:
komal=pd.DataFrame(dict_states)

In [16]:
komal

        states  districts
0  maharashtra     nagpur
1      gujarat      surat
2    tamilnadu  coimbatur
3    karnataka   banglore