In [2]:
import pandas as pd

In [3]:
exam=pd.read_csv(r"D:\Python\Python for Data Science\StudentsPerformance.csv")

In [4]:
exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
import numpy as np

In [6]:
import random

In [9]:
new_index= np.arange(0,1000)

In [10]:
new_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [11]:
#shufling the index
random.shuffle(new_index)
new_index

array([ 61, 841, 990, 727, 451,  83, 509, 870, 815, 356, 127, 109, 230,
       908, 643, 970, 277, 616, 943, 548, 447, 851,  41, 685, 657, 206,
       659, 133, 554, 798, 245,  65, 625, 862, 429, 204, 782,  90,   2,
       887, 776, 557, 955, 211,  55, 278, 475, 305, 380, 940, 702, 882,
       411, 471, 253, 445, 437, 757, 617, 928, 694, 508, 827, 830, 956,
        97, 165, 379, 946, 325, 608, 747, 890, 710, 832, 490, 175, 630,
       894, 704, 241, 134,  33, 432, 443, 796, 924, 878, 947, 781, 566,
       163, 641,  34,  36, 873, 459,   4, 262, 795, 110, 706, 517,  20,
       596, 655, 507, 821, 989, 347, 929, 466, 107, 902, 384, 904, 248,
       999, 736, 919, 516, 119, 398, 177, 478, 609, 775, 770, 833,  68,
       124, 101, 640, 774, 296, 910, 791, 666, 433, 627, 797, 731, 377,
       978,  62, 951, 415,  38, 553, 603, 819, 691, 151, 247, 155, 953,
       105, 558, 917,  70, 231, 840, 236, 611, 733, 131, 891, 590, 113,
       191, 251, 440, 354,  89, 751, 674, 386, 166, 295, 169, 391, 207,
       158, 545, 957, 200, 979, 976, 188, 705, 965, 363, 403, 837, 865,
       721, 408, 649,  15, 312, 780, 116, 435, 892, 587,  58, 713, 899,
       708, 759, 234,  78,  49, 328, 884, 410, 494, 343, 656, 226, 260,
       921, 197, 646, 602,  57, 572, 257,  25, 592, 573, 734, 212,  77,
       120, 267, 153, 728, 501, 333, 322, 684, 337, 359, 561, 213, 401,
       709, 703, 361, 388, 767, 304,  44, 474, 637, 985, 418,  13, 688,
       756, 439, 635, 828,  93, 522, 948, 885,  73, 765, 442, 114, 907,
       269, 222, 638, 588, 469, 909, 586, 464, 308, 817, 896, 834, 542,
       991, 341, 794, 618, 673, 607, 805,  60, 681, 142, 436, 700, 771,
       740, 156, 585, 707, 465, 288, 144, 600, 715, 938, 128, 593, 981,
       861, 170, 326,  29, 533, 249, 848, 457, 752, 601, 318, 866,  92,
       960, 644, 576, 298, 633,   1, 935, 802, 571, 670, 893, 879, 944,
       789, 137, 371, 448, 216, 316, 555, 808, 176,   5, 926, 467, 852,
       901,  11, 416, 838, 591, 632, 570, 208, 214, 975, 329, 419,  63,
       244, 154, 143, 168, 100, 152, 676, 140, 918, 741, 301, 567, 717,
       444, 777, 309,  88, 243, 562, 858, 620, 233, 314, 663, 737, 370,
       344, 927,  95, 192, 889, 699, 842, 362, 284,  99, 826, 748, 184,
        87, 932, 495, 578, 203, 980, 972, 417, 743, 723, 994, 692, 135,
       664, 552, 645, 686, 235,  84, 496, 532, 303, 967, 237, 784, 290,
       346,  98, 441,  46, 499, 331, 930, 680, 332, 300, 258, 461,  28,
       462, 383, 809, 210, 920, 521, 483, 753, 425,  23, 849, 289, 505,
       836, 689, 606, 614, 750,  39, 420, 263, 470, 355, 864, 624, 654,
       358, 722, 667, 786, 613, 194, 180, 563, 319, 148, 847, 867, 778,
       983, 193, 903, 397, 968,  51,  17, 716, 195, 933, 977, 986,  12,
       255, 695, 189, 714, 942, 293, 182, 270, 559, 183, 473, 631, 427,
       106, 454, 126,  14, 594, 330, 744, 498,  76, 678, 524,   8, 468,
       761, 306, 492, 973, 334, 261, 806, 390, 186, 404, 825, 758, 961,
       788, 900, 118, 785,  79, 431, 982,  85, 993,  21, 671,  53, 394,
       549, 502, 481, 259, 115, 897, 687, 690, 813, 479, 537, 622, 145,
       412, 424, 514, 914, 790, 497, 550, 476,  47, 831, 931, 987, 569,
        67, 898,  22, 382, 484,  32, 963, 527, 764, 974, 677, 367, 726,
       682, 407, 665, 647, 675, 349, 653, 446, 400, 906, 881, 612, 402,
       660, 599, 539,  66, 283, 147, 456, 626,  82, 387, 544, 405, 629,
       414, 167, 229, 489, 250, 199, 385, 954,  30, 202, 597, 374, 853,
       172,  94, 220, 129, 839, 530, 218, 323, 939, 389, 311, 458, 482,
       252, 730, 869, 271, 604, 855, 488,  31, 964, 287, 430,   9, 526,
       238, 227, 486, 511, 895, 810, 339, 619, 642,  26,  19, 178, 803,
       551, 850, 242, 138, 816,  86, 683, 450, 772, 541, 426, 528, 650,
       598, 112, 958, 372, 291, 823, 568, 962, 615, 276, 264, 661, 766,
       336, 843, 201,  50, 662,  24, 395, 992, 754, 327, 547, 745,  54,
       449, 161, 712, 696, 535, 279, 121, 297, 179, 228,   7, 610, 804,
       564, 763, 934, 773, 995, 423, 875, 945, 937, 846, 438, 223, 285,
       246, 422, 912, 749, 941, 393, 369, 971, 820, 348,  64,  72, 883,
       477,  81, 310, 141, 575,  59, 719, 580, 720, 583, 565, 221, 543,
       313, 409, 224, 392, 952, 149, 452, 769,  48, 104, 317, 669, 534,
        40, 373, 239, 577, 406, 286, 515, 793,  56,  52, 413, 453, 500,
       122, 801, 812, 536, 871, 779, 275,  45, 117, 966, 190, 923, 636,
        91, 335, 556, 364, 807, 159, 540, 742, 434, 368, 340, 254, 518,
       215, 760,  69, 868, 108, 487, 668, 711, 874, 648, 579, 725, 146,
       460, 560, 718, 854, 822, 845, 800, 504, 485, 272, 916, 360, 679,
       701, 574, 922,  71,   6, 160, 174, 472, 240, 998, 859, 768, 351,
       274,   3, 658, 132, 863, 273, 187, 162, 428, 915, 529, 123, 621,
       652, 787, 844, 399, 997, 352, 949, 157, 732, 324,  10, 746, 605,
        27, 755, 463, 762, 639, 905, 294, 925, 824,   0, 913, 520, 880,
       375, 792, 519, 205, 829, 582, 125, 860, 628, 198, 510, 280, 531,
       491, 634, 584, 376, 693, 350, 256, 315, 857, 698, 357, 996, 546,
       164,  43, 799, 523, 265, 651, 581,  80,  75, 268, 877, 130, 835,
       959, 818, 513, 814, 480, 589, 378, 811, 292, 338, 503,  42, 219,
       102, 735, 888, 623, 739, 936, 342, 729, 538, 185, 512, 181, 150,
       506, 111, 911, 136, 783, 595, 950, 672, 455, 697, 366, 872, 281,
       299, 217, 196, 381, 876, 103, 988, 493, 969, 173, 856, 209,  18,
       525, 266, 282, 345, 320,  74, 421,  96,  37,  35, 232, 365, 984,
       886, 321, 225, 353, 302,  16, 307, 139, 171, 396, 724, 738])

In [12]:
#create a new coloum with new index
exam['new_index']=new_index

In [14]:
exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,61
1,female,group C,some college,standard,completed,69,90,88,841
2,female,group B,master's degree,standard,none,90,95,93,990
3,male,group A,associate's degree,free/reduced,none,47,57,44,727
4,male,group C,some college,standard,none,76,78,75,451
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,139
996,male,group C,high school,free/reduced,none,62,55,55,171
997,female,group C,high school,free/reduced,completed,59,71,65,396
998,female,group D,some college,standard,completed,68,78,77,724
999,female,group D,some college,free/reduced,none,77,86,86,738