In [1]:
import pandas as pd

In [24]:
komal=pd.read_csv(r"D:\Python\Python for Data Science\StudentsPerformance.csv")

In [25]:
komal

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [26]:
komal.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [27]:
komal['language score'] = 70

In [28]:
komal

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

In [29]:
import numpy as np

In [30]:
language_score = np.arange(0, 1000)

In [32]:
language_score

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [37]:
len(language_score)

1000

In [39]:
komal['language score'] = language_score

In [42]:
komal

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [55]:
komal = np.random.randint(1, 200, size=1000)

In [59]:
komal

array([ 24, 123, 114, 187, 135,  53, 147,  79, 126,  64, 168, 132,  55,
        95, 115,  10,  36, 107,  43,  58, 152,  23, 135, 185,   9, 117,
        33, 121, 145,  86, 131,   5, 197, 157,  23, 195, 180, 115, 123,
        31, 124,  13,  99, 172,  64, 176, 143, 129, 162,  72,  91, 197,
        14, 104,  74, 145,  73,  35,  28, 155, 155, 162,  85, 100,  50,
         8, 190,  60,  91,   7, 132, 131, 187, 181,  43, 148,  51, 151,
       107,  33,  90, 182,  39,  44,  42,  74,  27,  37, 123, 172,  88,
        34,  22, 156,  68, 162, 148, 192,  88, 163,   6,  77, 191,  37,
        86,  72, 140,  88, 154,  34,  41, 141,  83,  13,  72,   3,  87,
        54,  80,  67,  56, 103,   9,  31,  16, 126,  62, 110, 129,  97,
        88, 136,  46, 104, 154,  79, 101,  19, 113,  33,  96, 122, 160,
       185, 164,  17,  76, 158, 154,  26, 138, 184,  92, 184, 148, 106,
       108, 153,  61,  24, 102, 149,  95, 174, 130, 154, 169, 172, 146,
       198,  60,  38,  72, 142,  71, 183,  35,  94,  27,  73,   3,  58,
        94,  90,  96, 184, 183,  23,  35,  55, 160,  12, 179, 171, 179,
       103, 189,  10, 185, 176,  41,  73, 175,  26, 138,  67,  79, 198,
       136,  53,  77, 156,  12,  96, 168,  88, 127, 125, 147,  39,  67,
        66,  91,  16, 188, 125,  51,  71, 119,   2,   8, 176, 142,  35,
       165, 115,  75,  26, 145, 195, 122,  30,  64,  87,  63, 108,   2,
       141,  80,  59,  17,  80, 187,  65, 157, 143, 115,  32,  63,  99,
       106,  27, 143, 172, 165,  62, 152, 114,  61, 107,  23,   4,  35,
       192,  61,  29, 151, 114, 103,  84,  53,  42, 173,  86,  74, 179,
        59,  61, 159,  47,  49,  38, 142,  70, 163,  10,   6,  12,  95,
        28, 176, 179,  76, 194, 179, 160,  79,  44, 182, 173,  56,  74,
       174,  71,   5,   2,  80, 151,   5,  55, 141, 173, 166, 152, 166,
       156, 159, 168,  10,  40,  11, 150,  74,   7, 125,  30, 156,  16,
        61, 140, 133,  16, 146, 166,  35, 118, 150, 128, 189, 119,  42,
       112,  44,  16,  90, 140,  92,   6, 146, 143,  28, 114,  52,  36,
       120, 164, 191, 163, 190, 134, 166, 157,  18, 138,  12, 101,  77,
       130, 146, 104, 180, 105,  50, 113,  44,  18, 177,  23, 133,  86,
        83, 154, 117, 188,  54,  91, 111,  76,   4,  30,  78,   7, 149,
        42, 130, 170, 158,  73,  71, 170, 123,  30, 152,  66, 121,  78,
       123, 159,  68, 171, 178, 123,  70, 161,  12,  25,  97, 150,  68,
        22,  69,  91,  84, 165,  31, 161, 121, 161, 185, 136, 157, 144,
       139, 142, 165, 124,  98, 185,  44,  63, 168, 176, 125,  91, 180,
         7,  51, 122,  74,  58,  48, 171,  12, 116,  78,  88, 116,  27,
       129, 103,  79,  97,  83,  72, 128, 103,   2, 116,  39, 135,  17,
        47,  74,  13, 176, 169, 112,  69, 118,  36, 137, 150,  84,  48,
       126,  58, 179,  87, 197, 133,  20,  44, 187, 121,   1, 182, 143,
       170,  73,  73,  86,  33,  80,  15,  64, 139, 154,   9,  25, 194,
       155,   6,  11,  75,  87, 173, 143,  43,  34,  39,  30,  93, 124,
       120,  50,  79, 148, 165,  68, 131, 133, 158, 157, 176,  51,  50,
       195, 114, 177, 154, 156,  87,  57,  85, 173,  51,  54,   8, 187,
       130,  95,  43, 171, 194,  74, 178,   2, 122,  97, 198, 159, 182,
        12, 170, 135,  68, 186,  23, 144,  36, 141, 115, 143, 125,  58,
       156,  81, 164,  45, 111, 150, 185, 109,  18, 189,   9, 127, 168,
        44, 181,  35, 181,  24, 165, 161,  22,  82,  56, 181, 171, 196,
       157, 183, 109,  45,  52, 176,  71, 199,  29,  22, 120,  85,  55,
        17, 183,  69,  14, 176, 185, 145, 131,  77,  89, 180,  65,  21,
       167,  69,  52,  77, 158,  83, 163,  27, 165,  46,  15,   1,   6,
       154, 124, 167, 192, 115, 156,  21, 111,  24, 183, 194, 190, 172,
       163, 101,  22,  22,  89,  57,  59,  82, 116,  78, 162, 172, 139,
        65, 129,  76, 139,  27, 133,  47,  59,  52,  47, 198, 103, 151,
        92,   1, 153, 122,  41, 100, 138,  15,  74, 178,  81,  99, 143,
        86,  13,  43, 184,   7,   2, 110, 164,  38, 174,  87, 177,  74,
       158,  80, 125, 171, 138,  96,  85,  43, 129,  12, 107, 181, 184,
        43,  53,  51,  74,  81, 108, 166,  26, 121,  41, 193, 165,  33,
       107, 166, 134,  10,  17,  45, 129,  15,   3, 169,   7,  47, 152,
       133, 164,  51,  96,  27, 111, 159,   8,  15, 117,  47,  96,  75,
       173,   9, 121, 165, 106, 199,  40, 140, 174,  42,  47, 181, 147,
        16, 121, 185,  43, 147,  47, 195, 101,  12,  81,  60,  59,  95,
       126,   9,  29,  94,  61,   8,  65, 124, 152,  68, 130, 109,  57,
       134,  89, 111, 194, 198, 176, 146,  94, 164, 126, 160,  53, 126,
       140,   1, 173,  95, 186, 187,  79,  22, 192,  36, 149,  88,  77,
        64, 175, 114, 183,  37, 186,  20, 169,  29,  78, 108,  50, 155,
        80, 118, 105, 104,  95,  54, 178,  20,  67,  95,  18,  71,  26,
       144,  88,  92, 107,  42,  36,  84,  49,   7,   5, 193, 159,  62,
       122, 114,   8, 152,  97,  35,   2, 114,  31, 106, 183, 131, 110,
        85, 135, 169,  17, 178,  38, 170,  61, 111, 155,  77,  30,  57,
       189,  80, 197,  41,  77, 139,  18, 188, 120, 125,  37, 162,  31,
       158,  89, 169,  59,  26, 161,  78, 137,  78,  78,  20, 131,  84,
        28, 148, 120, 158, 144,  93, 181, 161,  16,  76, 148,  41, 140,
         3,  36,  21, 163, 182, 166,  27, 188,  31, 181,   9,  22, 101,
        78, 182, 186,  40,  78,  36,   3, 197,  14,  15,  51,  94,   6,
       107, 198,  56, 154, 142,  32, 144,  87, 186, 178,  29, 131,  90,
       119,  97,  46, 155, 141, 119,  17,  80,  32,  67, 192, 103, 125,
       107, 191, 192, 102, 148,  86, 188,  24, 179,  34, 150, 132],
      dtype=int32)

In [60]:
print(min(int_language_score))
print(max(int_language_score))

1
199

In [50]:
komal['language score'] = int_language_score

In [61]:
komal

array([ 24, 123, 114, 187, 135,  53, 147,  79, 126,  64, 168, 132,  55,
        95, 115,  10,  36, 107,  43,  58, 152,  23, 135, 185,   9, 117,
        33, 121, 145,  86, 131,   5, 197, 157,  23, 195, 180, 115, 123,
        31, 124,  13,  99, 172,  64, 176, 143, 129, 162,  72,  91, 197,
        14, 104,  74, 145,  73,  35,  28, 155, 155, 162,  85, 100,  50,
         8, 190,  60,  91,   7, 132, 131, 187, 181,  43, 148,  51, 151,
       107,  33,  90, 182,  39,  44,  42,  74,  27,  37, 123, 172,  88,
        34,  22, 156,  68, 162, 148, 192,  88, 163,   6,  77, 191,  37,
        86,  72, 140,  88, 154,  34,  41, 141,  83,  13,  72,   3,  87,
        54,  80,  67,  56, 103,   9,  31,  16, 126,  62, 110, 129,  97,
        88, 136,  46, 104, 154,  79, 101,  19, 113,  33,  96, 122, 160,
       185, 164,  17,  76, 158, 154,  26, 138, 184,  92, 184, 148, 106,
       108, 153,  61,  24, 102, 149,  95, 174, 130, 154, 169, 172, 146,
       198,  60,  38,  72, 142,  71, 183,  35,  94,  27,  73,   3,  58,
        94,  90,  96, 184, 183,  23,  35,  55, 160,  12, 179, 171, 179,
       103, 189,  10, 185, 176,  41,  73, 175,  26, 138,  67,  79, 198,
       136,  53,  77, 156,  12,  96, 168,  88, 127, 125, 147,  39,  67,
        66,  91,  16, 188, 125,  51,  71, 119,   2,   8, 176, 142,  35,
       165, 115,  75,  26, 145, 195, 122,  30,  64,  87,  63, 108,   2,
       141,  80,  59,  17,  80, 187,  65, 157, 143, 115,  32,  63,  99,
       106,  27, 143, 172, 165,  62, 152, 114,  61, 107,  23,   4,  35,
       192,  61,  29, 151, 114, 103,  84,  53,  42, 173,  86,  74, 179,
        59,  61, 159,  47,  49,  38, 142,  70, 163,  10,   6,  12,  95,
        28, 176, 179,  76, 194, 179, 160,  79,  44, 182, 173,  56,  74,
       174,  71,   5,   2,  80, 151,   5,  55, 141, 173, 166, 152, 166,
       156, 159, 168,  10,  40,  11, 150,  74,   7, 125,  30, 156,  16,
        61, 140, 133,  16, 146, 166,  35, 118, 150, 128, 189, 119,  42,
       112,  44,  16,  90, 140,  92,   6, 146, 143,  28, 114,  52,  36,
       120, 164, 191, 163, 190, 134, 166, 157,  18, 138,  12, 101,  77,
       130, 146, 104, 180, 105,  50, 113,  44,  18, 177,  23, 133,  86,
        83, 154, 117, 188,  54,  91, 111,  76,   4,  30,  78,   7, 149,
        42, 130, 170, 158,  73,  71, 170, 123,  30, 152,  66, 121,  78,
       123, 159,  68, 171, 178, 123,  70, 161,  12,  25,  97, 150,  68,
        22,  69,  91,  84, 165,  31, 161, 121, 161, 185, 136, 157, 144,
       139, 142, 165, 124,  98, 185,  44,  63, 168, 176, 125,  91, 180,
         7,  51, 122,  74,  58,  48, 171,  12, 116,  78,  88, 116,  27,
       129, 103,  79,  97,  83,  72, 128, 103,   2, 116,  39, 135,  17,
        47,  74,  13, 176, 169, 112,  69, 118,  36, 137, 150,  84,  48,
       126,  58, 179,  87, 197, 133,  20,  44, 187, 121,   1, 182, 143,
       170,  73,  73,  86,  33,  80,  15,  64, 139, 154,   9,  25, 194,
       155,   6,  11,  75,  87, 173, 143,  43,  34,  39,  30,  93, 124,
       120,  50,  79, 148, 165,  68, 131, 133, 158, 157, 176,  51,  50,
       195, 114, 177, 154, 156,  87,  57,  85, 173,  51,  54,   8, 187,
       130,  95,  43, 171, 194,  74, 178,   2, 122,  97, 198, 159, 182,
        12, 170, 135,  68, 186,  23, 144,  36, 141, 115, 143, 125,  58,
       156,  81, 164,  45, 111, 150, 185, 109,  18, 189,   9, 127, 168,
        44, 181,  35, 181,  24, 165, 161,  22,  82,  56, 181, 171, 196,
       157, 183, 109,  45,  52, 176,  71, 199,  29,  22, 120,  85,  55,
        17, 183,  69,  14, 176, 185, 145, 131,  77,  89, 180,  65,  21,
       167,  69,  52,  77, 158,  83, 163,  27, 165,  46,  15,   1,   6,
       154, 124, 167, 192, 115, 156,  21, 111,  24, 183, 194, 190, 172,
       163, 101,  22,  22,  89,  57,  59,  82, 116,  78, 162, 172, 139,
        65, 129,  76, 139,  27, 133,  47,  59,  52,  47, 198, 103, 151,
        92,   1, 153, 122,  41, 100, 138,  15,  74, 178,  81,  99, 143,
        86,  13,  43, 184,   7,   2, 110, 164,  38, 174,  87, 177,  74,
       158,  80, 125, 171, 138,  96,  85,  43, 129,  12, 107, 181, 184,
        43,  53,  51,  74,  81, 108, 166,  26, 121,  41, 193, 165,  33,
       107, 166, 134,  10,  17,  45, 129,  15,   3, 169,   7,  47, 152,
       133, 164,  51,  96,  27, 111, 159,   8,  15, 117,  47,  96,  75,
       173,   9, 121, 165, 106, 199,  40, 140, 174,  42,  47, 181, 147,
        16, 121, 185,  43, 147,  47, 195, 101,  12,  81,  60,  59,  95,
       126,   9,  29,  94,  61,   8,  65, 124, 152,  68, 130, 109,  57,
       134,  89, 111, 194, 198, 176, 146,  94, 164, 126, 160,  53, 126,
       140,   1, 173,  95, 186, 187,  79,  22, 192,  36, 149,  88,  77,
        64, 175, 114, 183,  37, 186,  20, 169,  29,  78, 108,  50, 155,
        80, 118, 105, 104,  95,  54, 178,  20,  67,  95,  18,  71,  26,
       144,  88,  92, 107,  42,  36,  84,  49,   7,   5, 193, 159,  62,
       122, 114,   8, 152,  97,  35,   2, 114,  31, 106, 183, 131, 110,
        85, 135, 169,  17, 178,  38, 170,  61, 111, 155,  77,  30,  57,
       189,  80, 197,  41,  77, 139,  18, 188, 120, 125,  37, 162,  31,
       158,  89, 169,  59,  26, 161,  78, 137,  78,  78,  20, 131,  84,
        28, 148, 120, 158, 144,  93, 181, 161,  16,  76, 148,  41, 140,
         3,  36,  21, 163, 182, 166,  27, 188,  31, 181,   9,  22, 101,
        78, 182, 186,  40,  78,  36,   3, 197,  14,  15,  51,  94,   6,
       107, 198,  56, 154, 142,  32, 144,  87, 186, 178,  29, 131,  90,
       119,  97,  46, 155, 141, 119,  17,  80,  32,  67, 192, 103, 125,
       107, 191, 192, 102, 148,  86, 188,  24, 179,  34, 150, 132],
      dtype=int32)

In [53]:
# create random float numbers between 1 and 100
komal=np.random.uniform(1, 100, size=1000)

In [54]:
komal

array([87.96406188, 50.14702038, 64.73186108, 24.59824755, 28.89295061,
       44.70968959, 18.9469378 ,  7.80862359, 28.13959154, 11.0822862 ,
       28.49717471, 36.03077573, 94.78288216, 92.5701892 , 93.09740714,
       46.97383546, 73.01499932,  6.37171992, 69.96360606, 37.43398287,
       55.85766996, 28.36851509, 75.84222205,  1.26239279, 70.06900763,
       11.84883326,  3.76513257, 44.97441646, 59.51773282, 41.24736311,
       63.18044949, 21.59062067, 54.66745351, 35.17846245,  5.74875596,
       15.51557809, 28.84309748, 58.99708569, 29.59475731, 78.43524286,
       13.203114  , 19.1933851 , 63.4524524 , 78.93285696,  2.46102499,
       23.00529628, 65.41358288, 17.00011546, 12.06411572, 50.82612623,
       69.86781941, 82.26022115, 87.11185384, 13.62581751, 98.69079708,
       65.29901755,  5.00508338, 97.60434234, 12.6942742 , 92.58856084,
       61.73031195, 63.78371768, 85.51606996, 52.4720778 , 46.13197321,
       65.1084123 , 12.43175828, 24.98587831, 89.92185768, 73.86258327,
       99.30922395, 72.24742813, 24.60892968, 29.83568213, 91.60785703,
       40.36930768, 77.96372945, 12.05272699, 55.43760586,  3.85391504,
       60.3738472 , 63.35434885, 34.33194382,  7.90715687, 92.75734738,
       17.09069741, 44.4058516 , 55.07634164, 66.43032608, 13.8477428 ,
       17.5731353 , 72.06788499, 89.4523874 ,  2.77518015, 11.55998574,
       80.02773131, 96.53003691, 56.38869932, 83.85897124, 47.46053066,
       86.0496893 , 47.70929976, 49.86820708, 22.23607405, 81.76025411,
       47.66849997, 79.69678217, 52.37728   , 27.90567207, 27.75062236,
       63.03279524, 46.7273697 , 72.41525591, 33.03635995, 91.6286982 ,
       77.11963436, 63.59839671, 81.30410192, 85.97432103, 73.82067282,
        1.61922046, 76.2911503 , 94.63511743, 30.6376189 , 95.17078962,
       62.44901276, 62.25589277, 24.445011  , 60.85951131, 74.81186201,
       90.47138394, 75.38443908, 20.50220329, 59.46486029, 28.4396083 ,
       11.24429075, 55.1187336 , 79.73693333, 27.38498327, 59.42512797,
       31.94132374, 17.46101937,  1.63239231, 29.99206634, 98.39296283,
       50.6380413 , 96.25651399,  1.08285859,  9.25457828, 60.49069069,
       28.15080266, 36.40036348, 24.94344165, 49.04615079, 45.13609887,
       64.23145454, 27.13158681, 14.15413387, 76.09771253, 25.59650609,
       88.62358751, 58.16150112, 56.43839245, 58.36328595, 24.82011652,
       78.02493663, 61.72735386, 81.86754989, 38.59250747,  2.40756908,
       21.12031788, 31.29808686, 59.2404836 , 26.64735467, 60.90339942,
       91.36844512, 22.78600467, 57.55571734, 64.78439931, 44.61952661,
       62.02201112, 74.91889193, 79.98259871, 20.65154441, 28.53592895,
       65.79120435, 36.44804002, 84.48797008, 86.0332417 , 54.63158485,
       49.71406211, 80.426832  , 91.3580145 , 83.09425436, 58.74178017,
       75.84006474, 86.29596493, 54.6731066 ,  2.73500862, 45.63230507,
       91.60403228, 93.73426431, 53.17670211,  1.1097706 , 99.98717559,
       24.59910324, 20.40912725, 98.17399863, 53.02289969, 25.82356733,
       39.4836325 , 37.83876955, 69.87276283, 37.36975947, 85.04899433,
       80.79130239, 28.70157805, 79.6303349 , 40.43420002, 25.05605968,
       19.41726949, 46.48481047, 76.67300033, 73.02709361, 21.24370371,
       88.23531963, 50.0705698 , 92.83652473, 56.33917558, 80.17422967,
       28.18780456, 66.2328337 , 56.0991746 , 46.23018904, 27.19702955,
       10.8913396 , 47.58619942, 89.7396073 , 49.69675088, 31.8296209 ,
       75.33708118, 74.28083672, 34.94085698, 44.528278  ,  8.04136759,
       35.56245539, 97.19440944, 43.2455324 , 22.0600279 , 14.06313599,
       43.36573513, 17.09154842, 51.33449182, 63.46144483, 47.98017194,
       79.12361448, 62.58688522, 39.44535474, 55.20385225, 14.84065984,
       29.88193877, 79.3670014 ,  3.51344083, 22.74188183, 28.45747244,
       89.57105344, 83.19928235, 31.88154082, 65.54444162,  9.21870613,
        6.90923418, 83.76657659, 77.42611434, 84.71472926, 67.22948503,
       47.35970262, 70.17320852, 31.04998558, 80.02950373, 44.79477418,
       99.59318912, 17.96120462, 44.01745431,  8.11910668,  4.4050972 ,
       14.63816827, 24.26013256, 61.54152807, 90.83104009, 49.11721261,
       35.06860326, 34.70568408, 71.81387364, 61.17417652, 24.026722  ,
       77.27727169, 56.60774556, 75.4957389 , 57.09251991, 97.10272016,
       47.55778937, 36.07920922, 13.43901592, 90.79345731, 43.01335416,
       22.0646593 , 53.5926478 , 53.3528891 ,  3.03108785, 16.14475691,
       31.76788737, 93.86570934, 17.24168273, 64.43803747, 15.88221862,
       74.45146843, 79.42808529, 95.70891639, 46.3494184 , 35.28123806,
       82.02557329, 10.91671822, 10.33837639, 62.98977236, 13.38800117,
       64.36448735, 92.07487595, 94.29240535, 58.88136712, 42.9834996 ,
        4.74961074, 58.45405758, 36.01000628, 27.85597432, 40.9626843 ,
       87.37859143, 88.72858246, 16.52333049, 76.78504616, 46.77153543,
       11.79370982, 40.79514459, 51.42172547, 73.41312541, 65.38871704,
       18.51050104, 34.56517821, 27.16056393, 89.85531406,  1.60015336,
       98.36455377, 60.94604958, 19.11203001, 18.74340556, 85.63725737,
       68.09447647, 79.13517572,  5.3606265 , 10.19501919, 81.66174562,
       30.56111623, 19.32591247, 80.1973    , 30.80546281, 46.61056746,
       48.5910409 , 98.0882752 , 42.13998895, 30.52922566, 93.43337235,
       66.4624743 , 22.53500524, 42.18914921, 10.01825684, 34.60985167,
       87.36423699, 62.7767181 , 77.89093803, 57.10448155, 72.00361702,
       29.41610774, 74.88258932, 85.03692134, 91.7251304 , 51.0210722 ,
       27.2174404 , 69.6602978 , 49.05249568, 38.01114551, 60.65510706,
       37.5566638 , 40.15708489, 18.5690578 , 68.79900505, 87.2568779 ,
       64.09887021,  6.25825835, 12.04575009, 68.10637503, 89.05650538,
       95.40636787, 74.22598181, 73.00833132, 81.51126777, 23.21645607,
       76.86704748, 94.27374536, 76.8296011 ,  4.88067051, 56.31254022,
       99.46314307, 18.08965447, 71.97303786,  3.54283782, 49.70008409,
       21.9571717 , 16.46756742, 63.01680561, 32.25450981, 62.28005534,
       28.17421669, 66.57087168, 59.17970466, 55.25135216, 80.51291515,
       67.28232105, 14.43874314,  8.01162295, 92.79807641, 64.16259118,
       58.77992514,  4.65170695, 50.01275669, 15.73525764, 26.72089961,
       39.29140497, 37.39176087, 98.13700029, 93.04442632, 57.24546745,
       81.4005174 , 80.34459011, 58.1378156 , 37.48402925, 33.34608459,
       70.19955175, 65.30408812, 80.37917164, 68.49990247, 54.79647036,
       73.34367015, 11.98405866, 23.28127316,  1.86986248, 12.78450891,
       67.51049541, 39.42260013, 67.2380078 , 89.34735847, 99.70915413,
       93.97551162, 41.39281036, 75.88735781, 45.92158631, 84.43751237,
       83.44608493, 12.77555578, 20.93109656, 84.38203943, 73.47558869,
        9.25802464, 18.4015657 , 88.22993659, 56.88312807, 11.40388265,
       33.69185188, 20.00600959, 37.20294182, 89.05090275, 93.40290989,
       24.45892868, 86.28271873, 20.89939791, 88.01304506,  9.28720892,
       55.93414785, 23.59880644, 93.38554043, 84.41344727, 24.41635417,
       28.84042911, 48.45023609, 58.96740356, 86.08117101, 40.35600159,
       84.80598971, 70.40881485, 27.2102836 , 69.0523889 , 59.32937455,
       36.30237815, 91.14406526, 23.35222046, 35.56150743, 20.80491507,
        1.99280563, 52.51570533, 64.04678941, 72.41972871,  7.58082141,
       74.09633029, 40.09783581, 31.46336834,  2.5004544 , 11.03519525,
       25.03538084, 49.66013139, 79.18832326, 74.72241584, 57.36285965,
       48.84604151, 81.03544001, 25.87629913, 35.28754853, 41.77018833,
       50.39865621,  2.27099697, 85.49021047, 79.07105878, 39.29680914,
       85.02491133, 56.11814626, 34.79544991, 48.17182275, 24.82229079,
       77.17699149, 54.2064631 , 23.17599469, 84.17510094, 80.95844101,
       64.64065704, 48.99251961, 62.21133064, 24.46564858, 48.40763344,
       55.08804366, 77.60865392, 85.95189842, 94.90059462, 38.43841731,
       19.307795  , 33.92757926, 40.43868471, 39.61860653, 24.97585387,
       79.49894233, 43.12521866, 54.3907903 , 92.96871128, 93.86067403,
       41.83884701, 37.23113003, 95.82072214, 21.08385348, 87.57737573,
       54.81000577, 66.17836536, 98.38164963, 89.82523471, 93.60568318,
       96.97636296, 50.28208802,  8.19178028, 53.30975628,  6.41514973,
       79.31820513, 10.41533663, 20.77239807, 73.13147747, 90.60061045,
       11.26922948, 93.57697157, 52.8670166 , 19.25691828, 25.47648375,
       12.3451737 , 54.82118532, 28.08726225, 21.74867117, 35.84386027,
       79.81176971, 19.73305247, 88.99029181, 77.78445853, 67.9079816 ,
        4.10271358, 95.33249801, 51.70283423, 62.49125116, 47.67298632,
       46.43248628, 65.75332716, 81.81136587, 80.88369403, 22.53249089,
       38.74185418, 15.52214886, 56.24543117, 36.73768824, 30.51798282,
       22.56157968, 96.22658118, 50.15939566, 64.55341291, 93.937362  ,
       56.73996765, 11.34211794, 61.12072261, 52.14628394, 81.75719827,
        9.41822992, 43.1134472 , 72.06112164, 57.26182704, 11.79422958,
       55.603423  , 57.80733762, 32.30046833, 80.96341195, 51.69484603,
       25.66940703, 27.63933905, 35.46219845, 53.34966427, 51.8882681 ,
       84.38713054, 70.92083743, 35.03407138, 76.01260594, 32.64083144,
       51.59160583, 77.2876937 , 47.04686276,  6.86879131, 99.23224038,
       57.54464119,  9.70834128, 55.39173282, 27.38801439, 82.19061287,
       56.78461703, 26.95908113, 57.27054167, 32.36368566, 41.51623765,
       50.53637841, 37.84842592,  4.52603437, 59.32982823, 59.02916173,
       15.72566577, 86.63905549, 43.22729581, 12.62657497,  8.12733437,
       10.9008934 , 27.23420016, 44.5424385 , 35.27062611, 93.00751615,
       11.94236089, 27.83338857, 26.16728234, 55.25598723, 90.11732862,
       96.92076435, 76.39036355, 26.52253332, 51.32510158, 44.16301432,
       83.67314441, 75.65852793, 90.37011437, 87.75657907, 34.45490872,
       13.60669282,  7.72566578, 96.02239184, 64.41141377, 46.1682013 ,
        9.24408297, 19.51686798, 27.35614849, 20.31258042,  3.70123461,
       28.55479724, 27.3214063 , 48.26587642, 19.84699594, 10.67532843,
       45.77708518, 60.80460294, 27.22417437, 25.40610682, 58.74216006,
       27.69204702, 83.96519206, 28.80319183, 98.44500033, 15.47749752,
       81.13379382, 94.13047007, 57.37210322, 91.92288538, 72.43263057,
        2.86077416, 64.5563625 , 44.12865418, 79.63764359, 50.91573535,
       81.00968247, 85.87334373, 62.9972195 , 87.86544538,  1.90233568,
       71.8056307 , 83.09684987, 48.77494556, 75.81295575, 27.29023771,
       91.68265756, 70.59973456, 32.99481536, 95.47655546,  9.01383874,
       43.66983267, 96.72569131, 74.60802122, 48.72200281, 19.66938307,
       65.55046011, 40.50960022, 24.42600337, 93.61400679, 63.5771795 ,
       97.89964023, 28.35923224, 18.80689975, 16.13135296, 70.69233839,
       44.15485138, 90.81811046, 84.77782696, 91.98344092, 28.72070743,
       32.77892142, 17.90881945, 73.27341515, 91.79978757, 78.37117004,
       95.80792181,  6.87729733, 68.97975939, 56.15151346, 68.50366837,
       54.58094442, 22.44469299, 85.59110487, 47.97770477, 57.0403959 ,
       67.92394271, 56.85453671,  7.92805262, 78.65185897, 87.38776704,
       87.45813672, 33.66270345, 57.68241689, 46.61522134, 57.30428197,
       64.24134782, 29.35746539, 96.88884537, 99.49353943, 42.63914545,
       71.26111179, 20.32009914, 65.96044229, 11.8730637 , 51.40958944,
       99.35397474, 32.15366957, 86.62469784, 81.78954409, 15.70349832,
        7.26361641, 60.72463967, 56.82083117, 43.48189882, 57.71559038,
       27.1065585 , 41.18597764,  3.38103565, 64.92754051, 44.98034192,
       19.51759265, 63.32475776, 85.2248569 , 43.00122674, 69.72718413,
       91.81360552, 26.03047933, 56.98921517, 30.95111225,  8.69292843,
       99.2441136 , 34.11748181, 61.48469694, 11.35616324,  3.29008481,
       94.46054279, 35.29136947, 31.95272948, 79.37319689,  3.18266127,
       81.66764797, 73.38910345, 21.26159654, 28.93941777, 16.04468725,
       25.92579751, 40.4544242 , 68.21097061, 30.25324502, 46.69899047,
       82.32844033, 64.5210367 , 99.3173809 , 76.82979665, 62.48602947,
       44.9337711 , 38.81795896, 34.09599384, 69.38698775, 21.92220712,
       32.92736553, 55.1385654 , 30.60334527,  7.08183034, 12.94113077,
       53.86115265, 92.18326899, 93.79768096, 43.52061435, 79.73166123,
        6.71340896, 76.12910104, 65.94859685, 37.10688779, 72.36998182,
        6.0212245 , 18.59003131, 77.0977806 , 65.92657564, 35.89622498,
       27.46967484, 24.81265261, 57.78284626, 92.00821921, 97.84973088,
       79.01452108, 27.83788607, 46.74483494, 26.28120524, 18.52826626,
       74.58904254, 73.31126822, 60.42963518, 80.11890571, 76.2713813 ,
       16.74198793, 10.59448179, 21.60966378, 14.90591565, 22.27428734,
       86.53371625,  4.2000815 , 49.59553738, 83.79953043, 38.24020341,
       80.25928779, 65.75428776, 54.79656877, 17.55624575, 39.36762931,
       80.3987911 , 42.78483603, 46.31428653, 75.57571152, 24.13514239,
       38.88294346, 34.05582199, 59.45050003, 73.49429023, 83.43363582,
       70.92903874, 50.38894466,  1.15114595, 24.60461027, 73.38968068,
       46.32797154, 42.64437166, 12.44839414, 94.01610763,  5.6634456 ,
       98.86742805, 36.18119187, 65.02238728, 76.14986649, 35.30496554,
       47.35665492, 92.41263894, 36.92505086, 38.56445156, 52.88429553,
       83.32874735, 85.43113016, 75.3380599 , 17.84914846, 33.68039185,
       11.23026218, 86.76516548, 51.9929029 , 28.27617943, 19.59642136,
       75.96294238, 59.78483595, 11.16330389, 98.92425878, 44.15341317,
       39.47541979, 22.95616467, 31.62382139, 10.11642248, 25.97805103,
       21.01924919, 68.8042306 , 10.46114918, 91.25491711, 78.47899462,
        6.49366519, 11.30855073, 10.52004175, 33.30698091,  5.32427663,
       33.23045586, 73.28116417, 56.64106235, 27.47325318, 25.67830934,
       97.59559562, 15.81906778, 97.58833382, 10.46260012, 85.65098292,
       14.62247062, 32.88057193, 36.26233896, 79.52782303, 57.60999834,
       44.65959661, 92.06413091, 56.49234461,  9.90096048,  9.82391249,
       52.67440421, 19.31436944, 53.97716973, 28.37959071, 68.09800536,
       75.44309416, 85.57557104, 68.46147419, 27.73445315, 35.8930487 ,
       74.48665473,  4.69943823, 16.07385977, 41.67759035, 65.31389066,
       79.70258398, 92.60435463, 18.77810314, 78.00760338, 99.82349163,
       13.89894778, 61.85034956, 19.47661102, 13.02330933, 30.56563085])

In [62]:
print(min(komal))
print(max(komal))

1
199