In [61]:
import pandas as pd

In [63]:
komal=pd.read_csv(r"D:\Python\Python for Data Science\StudentsPerformance.csv")
komal.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [64]:
import numpy as np

In [65]:
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

In [66]:
# create a series using the random numbers
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [67]:
# using assign() to add multiple columns
komal = komal.assign(score1=series1, score2=series2)

In [68]:
komal

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,20,82
1,female,group C,some college,standard,completed,69,90,88,20,12
2,female,group B,master's degree,standard,none,90,95,93,29,22
3,male,group A,associate's degree,free/reduced,none,47,57,44,76,52
4,male,group C,some college,standard,none,76,78,75,96,60
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,44,91
996,male,group C,high school,free/reduced,none,62,55,55,42,25
997,female,group C,high school,free/reduced,completed,59,71,65,76,91
998,female,group D,some college,standard,completed,68,78,77,54,99
999,female,group D,some college,free/reduced,none,77,86,86,99,13

In [69]:
# using insert() to add a column at a specific position
komal.insert(1, 'test', series1)

In [70]:
komal

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,20,group B,bachelor's degree,standard,none,72,72,74,20,82
1,female,20,group C,some college,standard,completed,69,90,88,20,12
2,female,29,group B,master's degree,standard,none,90,95,93,29,22
3,male,76,group A,associate's degree,free/reduced,none,47,57,44,76,52
4,male,96,group C,some college,standard,none,76,78,75,96,60
...,...,...,...,...,...,...,...,...,...,...,...
995,female,44,group E,master's degree,standard,completed,88,99,95,44,91
996,male,42,group C,high school,free/reduced,none,62,55,55,42,25
997,female,76,group C,high school,free/reduced,completed,59,71,65,76,91
998,female,54,group D,some college,standard,completed,68,78,77,54,99
999,female,99,group D,some college,free/reduced,none,77,86,86,99,13

In [1]:
import pandas as pd

In [8]:
minal=pd.read_csv(r"D:\Python\Python for Data Science\StudentsPerformance.csv")
minal.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [9]:
minal.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [10]:
import numpy as np

In [12]:
# create random numbers for our new score columns
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

In [13]:
# create a series using the random numbers
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [14]:
# using assign() to add multiple columns
minal = minal.assign(score1=series1, score2=series2)

In [15]:
minal

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,1,37
1,female,group C,some college,standard,completed,69,90,88,13,20
2,female,group B,master's degree,standard,none,90,95,93,44,31
3,male,group A,associate's degree,free/reduced,none,47,57,44,73,91
4,male,group C,some college,standard,none,76,78,75,46,59
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,44,28
996,male,group C,high school,free/reduced,none,62,55,55,34,65
997,female,group C,high school,free/reduced,completed,59,71,65,23,28
998,female,group D,some college,standard,completed,68,78,77,58,30
999,female,group D,some college,free/reduced,none,77,86,86,96,31

In [19]:
# using insert() to add a column at a specific position
minal.insert(3, 'test3', series1)

In [20]:
minal

,gender,test,race/ethnicity,test3,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,1,group B,1,bachelor's degree,standard,none,72,72,74,1,37
1,female,13,group C,13,some college,standard,completed,69,90,88,13,20
2,female,44,group B,44,master's degree,standard,none,90,95,93,44,31
3,male,73,group A,73,associate's degree,free/reduced,none,47,57,44,73,91
4,male,46,group C,46,some college,standard,none,76,78,75,46,59
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,44,group E,44,master's degree,standard,completed,88,99,95,44,28
996,male,34,group C,34,high school,free/reduced,none,62,55,55,34,65
997,female,23,group C,23,high school,free/reduced,completed,59,71,65,23,28
998,female,58,group D,58,some college,standard,completed,68,78,77,58,30
999,female,96,group D,96,some college,free/reduced,none,77,86,86,96,31

In [21]:
# using insert() to add a column at a specific position
minal.insert(4, 'test4', series1)
minal

,gender,test,race/ethnicity,test3,test4,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,1,group B,1,1,bachelor's degree,standard,none,72,72,74,1,37
1,female,13,group C,13,13,some college,standard,completed,69,90,88,13,20
2,female,44,group B,44,44,master's degree,standard,none,90,95,93,44,31
3,male,73,group A,73,73,associate's degree,free/reduced,none,47,57,44,73,91
4,male,46,group C,46,46,some college,standard,none,76,78,75,46,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,44,group E,44,44,master's degree,standard,completed,88,99,95,44,28
996,male,34,group C,34,34,high school,free/reduced,none,62,55,55,34,65
997,female,23,group C,23,23,high school,free/reduced,completed,59,71,65,23,28
998,female,58,group D,58,58,some college,standard,completed,68,78,77,58,30
999,female,96,group D,96,96,some college,free/reduced,none,77,86,86,96,31

In [23]:
import pandas as pd

data = [2, 4, 4, 4, 6]
df = pd.Series(data)

# Sample standard deviation (Default: ddof=1)
sample_sd = df.std()
print(f"Pandas Sample SD: {sample_sd:.3f}")  # Output: 1.414

Pandas Sample SD: 1.414