In [36]:
import pandas as pd

In [38]:
data = [[1,3],[2,3],[5,5]]

In [ ]:
df = pd.DataFrame(data,index=['row1', 'row2', 'row3'],
                 columns=['col1', 'col2'])

In [ ]:
df

      col1  col2
row1     1     3
row2     2     3
row3     5     5

In [ ]:
import numpy as np

In [ ]:
data1 = np.array([[1, 4,3,4], [2,1,5, 5], [3,3,1, 6],[4,3,2,1],[1,2,3,5]])

In [ ]:
data1

array([[1, 4, 3, 4],
       [2, 1, 5, 5],
       [3, 3, 1, 6],
       [4, 3, 2, 1],
       [1, 2, 3, 5]])

In [ ]:
data

[[1, 3], [2, 3], [5, 5]]

In [ ]:
df = pd.DataFrame(data1,index=['row1', 'row2', 'row3','row4','row5'],
                 columns=['col1', 'col2','col3','col4'])

In [ ]:
df

      col1  col2  col3  col4
row1     1     4     3     4
row2     2     1     5     5
row3     3     3     1     6
row4     4     3     2     1
row5     1     2     3     5

In [32]:
# lists used for this example
states = ["California", "Texas", "Florida", "New York"]
population = [39613493, 29730311, 21944577, 19299981]

In [33]:
# Storing lists within a dictionary
dict_states = {'States': states, 'Population': population}
dict_states

{'States': ['California', 'Texas', 'Florida', 'New York'],
 'Population': [39613493, 29730311, 21944577, 19299981]}

In [34]:
df_population = pd.DataFrame(dict_states)

In [35]:
df_population

       States  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

In [28]:
import pandas as pd

In [24]:
df = pd.read_csv("D:\Python\Python for Data Science\StudentsPerformance.csv")
df

<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2104\4079192808.py:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
  df = pd.read_csv("D:\Python\Python for Data Science\StudentsPerformance.csv")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [42]:
data2= [[1,3],[2,3],[5,5],[6,8]]

In [43]:
df = pd.DataFrame(data2,index=['row1','row2','row3','row4'],
                 columns=['col1','col2'])

In [ ]:
df

      col1  col2
row1     1     3
row2     2     3
row3     5     5
row4     6     8

In [5]:
data3=[[1,2,3,4],[5,6,7,9],[6,8,9,5],[8,9,7,3]]

In [12]:
df = pd.DataFrame(data3,index=['row1','row2','row3','row4'],
                 columns=['col1','col2','col3', 'col4'])

In [13]:
import pandas as pd

In [14]:
df

      col1  col2  col3  col4
row1     1     2     3     4
row2     5     6     7     9
row3     6     8     9     5
row4     8     9     7     3

In [ ]:
# dictionery 
states = ["india" ,"California", "Texas", "Florida", "New York","china"]
population = [89764458, 39613493, 29730311, 21944577, 19299981,98765445]

In [19]:
dict_states = {'States': states, 'Population': population}
dict_states

{'States': ['india', 'California', 'Texas', 'Florida', 'New York', 'china'],
 'Population': [89764458, 39613493, 29730311, 21944577, 19299981, 98765445]}

In [30]:
df_population = pd.DataFrame(dict_states)

In [31]:
df_population

       States  Population
0       india    89764458
1  California    39613493
2       Texas    29730311
3     Florida    21944577
4    New York    19299981
5       china    98765445

In [ ]:
# dictionery
states=["maharashtra","madhya pradesh","rajashtan","gujarat","chennai"]
district=['nagpur', 'bophal', 'jaislmar', 'surat','madras']

In [41]:
states_dist = {'States': states, 'district': district}
states_dist

{'States': ['maharashtra',
  'madhya pradesh',
  'rajashtan',
  'gujarat',
  'chennai'],
 'district': ['nagpur', 'bophal', 'jaislmar', 'surat', 'madras']}

In [55]:
df_data= pd.DataFrame(states_dist)

In [64]:
df_data

           States  district
0     maharashtra    nagpur
1  madhya pradesh    bophal
2       rajashtan  jaislmar
3         gujarat     surat
4         chennai    madras

In [46]:
# creating a data base from csv file
df_exams = pd.read_csv('StudentsPerformance.csv')

In [47]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [49]:
import numpy as np

In [51]:
# creating an array
data= np.array([[12,23,34,],[67,98,65],[89,65,43]])

In [52]:
data

array([[12, 23, 34],
       [67, 98, 65],
       [89, 65, 43]])

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("D:\Python\Python for Data Science\StudentsPerformance.csv")
df

<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_21324\4079192808.py:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
  df = pd.read_csv("D:\Python\Python for Data Science\StudentsPerformance.csv")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [7]:
import os
os.getcwd()

'd:\\Python\\Python for Data Science'

In [1]:
import numpy as np

In [3]:
abc = np.array([[1, 4,3,4], [2,1,5, 5],[4,3,2,1],[1,2,3,5]])

In [4]:
abc

array([[1, 4, 3, 4],
       [2, 1, 5, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 5]])

In [5]:
import numpy as np

In [9]:
komal=np.array([[2,3,4],[4,5,6],[8,9,7]])

In [10]:
komal

array([[2, 3, 4],
       [4, 5, 6],
       [8, 9, 7]])

In [12]:
import pandas as pd

In [13]:
komal= [[1,3],[2,3],[5,5],[6,8]]

In [15]:
result= pd.DataFrame(komal,index=['row1','row2','row3','row4'],
                 columns=['col1','col2'])

In [16]:
result

      col1  col2
row1     1     3
row2     2     3
row3     5     5
row4     6     8

In [17]:
import pandas as pd

In [18]:
minal=([[2,3],[3,6],[8,9]])

In [19]:
result=pd.DataFrame(minal,index=['row1','row2','row3'],
                 columns=['col1','col2'])

In [20]:
result

      col1  col2
row1     2     3
row2     3     6
row3     8     9

In [21]:
import pandas as pd

In [ ]:
df=pd.read_csv()